local v7 = {
    ["Los Lucky Blocks"] = {
        HideFromIndex = true,
        Rarity = "Admin",
        Generation = 0,
        Price = 250000000,
        LuckyBlock = table: 0xe7789cbd659c2218,
        DisplayName = "Los Lucky Blocks",
    },
    ["Secret Lucky Block"] = {
        HideFromIndex = true,
        RoadWeight = 7e-07,
        Rarity = "Secret",
        Generation = 0,
        Price = 750000000,
        LuckyBlock = table: 0xced7d4b7f7ae7628,
        DisplayName = "Lucky Block",
    },
    ["Mythic Lucky Block"] = {
        HideFromIndex = true,
        RoadWeight = 0.05,
        Rarity = "Mythic",
        Generation = 0,
        Price = 2500000,
        LuckyBlock = table: 0x89791b897c27d468,
        DisplayName = "Lucky Block",
    },
    ["Los Taco Blocks"] = {
        SpawnVFX = "Taco",
        Rarity = "Taco",
        Price = 300000000,
        DisplayName = "Los Taco Blocks",
        HideFromIndex = true,
        Generation = 0,
        IsEnabled = function: 0xe1a6b749fbfb1438,
        LuckyBlock = table: 0x30fc76fd2fd7a478,
        SpawnDelay = 3,
    },
    ["Brainrot God Lucky Block"] = {
        HideFromIndex = true,
        RoadWeight = 0.001,
        Rarity = "Brainrot God",
        Generation = 0,
        Price = 25000000,
        LuckyBlock = table: 0xd410aa8a5db0e6e8,
        DisplayName = "Lucky Block",
    },
    ["Admin Lucky Block"] = {
        HideFromIndex = true,
        Rarity = "Admin",
        Generation = 0,
        Price = 100000000,
        LuckyBlock = table: 0x3d5441dec133c958,
        DisplayName = "Lucky Block",
    },
    ["Taco Lucky Block"] = {
        HideFromIndex = true,
        SpawnVFX = "Taco",
        Rarity = "Taco",
        Generation = 0,
        Price = 50000000,
        SpawnDelay = 3,
        LuckyBlock = table: 0x84628d385a4c5388,
        DisplayName = "Lucky Block",
    },
    ["Spooky Lucky Block"] = {
        HideFromIndex = true,
        SpawnVFX = "Spooky",
        Rarity = "Spooky",
        Generation = 0,
        Price = 350000000,
        SpawnDelay = 3,
        LuckyBlock = table: 0x52e781d76762cf48,
        DisplayName = "Spooky Lucky Block",
    },
    ["Noobini Pizzanini"] = {
        RoadWeight = 100,
        Rarity = "Common",
        Generation = 1,
        Price = 25,
        DisplayName = "Noobini Pizzanini",
    },
    ["Lirilì Larilà"] = {
        RoadWeight = 55,
        Rarity = "Common",
        Generation = 3,
        Price = 250,
        DisplayName = "Lirilì Larilà",
    },
    ["Tim Cheese"] = {
        RoadWeight = 50,
        Rarity = "Common",
        Generation = 5,
        Price = 500,
        DisplayName = "Tim Cheese",
    },
    ["Fluriflura"] = {
        RoadWeight = 45,
        Rarity = "Common",
        Generation = 7,
        Price = 750,
        DisplayName = "Fluriflura",
    },
    ["Talpa Di Fero"] = {
        RoadWeight = 43,
        Rarity = "Common",
        Generation = 9,
        Price = 1000,
        DisplayName = "Talpa Di Fero",
    },
    ["Svinina Bombardino"] = {
        RoadWeight = 40,
        Rarity = "Common",
        Generation = 10,
        Price = 1250,
        DisplayName = "Svinina Bombardino",
    },
    ["Raccooni Jandelini"] = {
        Price = 1350,
        Generation = 12,
        Rarity = "Common",
        DisplayName = "Raccooni Jandelini",
    },
    ["Tartaragno"] = {
        Price = 1500,
        Generation = 13,
        Rarity = "Common",
        DisplayName = "Tartaragno",
    },
    ["Pipi Kiwi"] = {
        RoadWeight = 37,
        Rarity = "Common",
        Generation = 13,
        Price = 1500,
        DisplayName = "Pipi Kiwi",
    },
    ["Pipi Corni"] = {
        Price = 1750,
        Generation = 14,
        Rarity = "Common",
        DisplayName = "Pipi Corni",
    },
    ["Trippi Troppi"] = {
        RoadWeight = 30,
        Rarity = "Rare",
        Generation = 15,
        Price = 2000,
        DisplayName = "Trippi Troppi",
    },
    ["Gangster Footera"] = {
        RoadWeight = 25,
        Rarity = "Rare",
        Generation = 30,
        Price = 4000,
        DisplayName = "Gangster Footera",
    },
    ["Bandito Bobritto"] = {
        RoadWeight = 22.5,
        Rarity = "Rare",
        Generation = 35,
        Price = 4500,
        DisplayName = "Bandito Bobritto",
    },
    ["Boneca Ambalabu"] = {
        RoadWeight = 20,
        Rarity = "Rare",
        Generation = 40,
        Price = 5000,
        DisplayName = "Boneca Ambalabu",
    },
    ["Cacto Hipopotamo"] = {
        RoadWeight = 18.5,
        Rarity = "Rare",
        Generation = 50,
        Price = 6500,
        DisplayName = "Cacto Hipopotamo",
    },
    ["Ta Ta Ta Ta Sahur"] = {
        RoadWeight = 17,
        Rarity = "Rare",
        Generation = 55,
        Price = 7500,
        DisplayName = "Ta Ta Ta Ta Sahur",
    },
    ["Cupcake Koala"] = {
        Price = 8000,
        Generation = 60,
        Rarity = "Rare",
        DisplayName = "Cupcake Koala",
    },
    ["Tric Trac Baraboom"] = {
        RoadWeight = 15,
        Rarity = "Rare",
        Generation = 65,
        Price = 9000,
        DisplayName = "Tric Trac Baraboom",
    },
    ["Pipi Avocado"] = {
        Price = 9500,
        Generation = 70,
        Rarity = "Rare",
        DisplayName = "Pipi Avocado",
    },
    ["Pinealotto Fruttarino"] = {
        Price = 9750,
        Generation = 75,
        Rarity = "Rare",
        DisplayName = "Pinealotto Fruttarino",
    },
    ["Cappuccino Assassino"] = {
        RoadWeight = 13,
        Rarity = "Epic",
        Generation = 75,
        Price = 10000,
        DisplayName = "Cappuccino Assassino",
    },
    ["Bandito Axolito"] = {
        Price = 12500,
        Generation = 90,
        Rarity = "Epic",
        DisplayName = "Bandito Axolito",
    },
    ["Brr Brr Patapim"] = {
        RoadWeight = 10,
        Rarity = "Epic",
        Generation = 100,
        Price = 15000,
        DisplayName = "Brr Brr Patapim",
    },
    ["Avocadini Antilopini"] = {
        RoadWeight = 8.5,
        Rarity = "Epic",
        Generation = 115,
        Price = 17500,
        DisplayName = "Avocadini Antilopini",
    },
    ["Trulimero Trulicina"] = {
        RoadWeight = 7,
        Rarity = "Epic",
        Generation = 125,
        Price = 20000,
        DisplayName = "Trulimero Trulicina",
    },
    ["Bambini Crostini"] = {
        RoadWeight = 6,
        Rarity = "Epic",
        Generation = 135,
        Price = 22500,
        DisplayName = "Bambini Crostini",
    },
    ["Malame Amarele"] = {
        Price = 23500,
        Generation = 140,
        Rarity = "Epic",
        DisplayName = "Malame Amarele",
    },
    ["Bananita Dolphinita"] = {
        RoadWeight = 5,
        Rarity = "Epic",
        Generation = 150,
        Price = 25000,
        DisplayName = "Bananita Dolphinita",
    },
    ["Perochello Lemonchello"] = {
        RoadWeight = 4.5,
        Rarity = "Epic",
        Generation = 160,
        Price = 27500,
        DisplayName = "Perochello Lemonchello",
    },
    ["Brri Brri Bicus Dicus Bombicus"] = {
        RoadWeight = 3.5,
        Rarity = "Epic",
        Generation = 175,
        Price = 30000,
        DisplayName = "Brri Brri Bicus Dicus Bombicus",
    },
    ["Burbaloni Loliloli"] = {
        RoadWeight = 1,
        Rarity = "Legendary",
        Generation = 200,
        Price = 35000,
        DisplayName = "Burbaloni Loliloli",
    },
    ["Avocadini Guffo"] = {
        RoadWeight = 3,
        Rarity = "Epic",
        Generation = 225,
        Price = 35000,
        DisplayName = "Avocadini Guffo",
    },
    ["Ti Ti Ti Sahur"] = {
        Price = 37500,
        Generation = 225,
        Rarity = "Epic",
        DisplayName = "Ti Ti Ti Sahur",
    },
    ["Mangolini Parrocini"] = {
        Price = 38500,
        Generation = 235,
        Rarity = "Epic",
        DisplayName = "Mangolini Parrocini",
    },
    ["Frogato Pirato"] = {
        Price = 39000,
        Generation = 240,
        Rarity = "Epic",
        DisplayName = "Frogato Pirato",
    },
    ["Salamino Penguino"] = {
        RoadWeight = 2.5,
        Rarity = "Epic",
        Generation = 250,
        Price = 40000,
        DisplayName = "Salamino Penguino",
    },
    ["Doi Doi Do"] = {
        Price = 41000,
        Generation = 260,
        Rarity = "Epic",
        DisplayName = "Doi Doi Do",
    },
    ["Wombo Rollo"] = {
        RoadWeight = 1.75,
        Rarity = "Epic",
        Generation = 275,
        Price = 42500,
        DisplayName = "Wombo Rollo",
    },
    ["Penguino Cocosino"] = {
        Price = 45000,
        Generation = 300,
        Rarity = "Epic",
        DisplayName = "Penguino Cocosino",
    },
    ["Chimpanzini Bananini"] = {
        RoadWeight = 0.75,
        Rarity = "Legendary",
        Generation = 300,
        Price = 50000,
        DisplayName = "Chimpanzini Bananini",
    },
    ["Mummio Rappitto"] = {
        Price = 47500,
        Generation = 325,
        Rarity = "Epic",
        DisplayName = "Mummio Rappitto",
    },
    ["Tirilikalika Tirilikalako"] = {
        Price = 75000,
        Generation = 450,
        Rarity = "Legendary",
        DisplayName = "Tirilikalika Tirilikalako",
    },
    ["Ballerina Cappuccina"] = {
        RoadWeight = 0.55,
        Rarity = "Legendary",
        Generation = 500,
        Price = 100000,
        DisplayName = "Ballerina Cappuccina",
    },
    ["Chef Crabracadabra"] = {
        RoadWeight = 0.5,
        Rarity = "Legendary",
        Generation = 600,
        Price = 150000,
        DisplayName = "Chef Crabracadabra",
    },
    ["Lionel Cactuseli"] = {
        RoadWeight = 0.47,
        Rarity = "Legendary",
        Generation = 650,
        Price = 175000,
        DisplayName = "Lionel Cactuseli",
    },
    ["Glorbo Fruttodrillo"] = {
        RoadWeight = 0.45,
        Rarity = "Legendary",
        Generation = 750,
        Price = 200000,
        DisplayName = "Glorbo Fruttodrillo",
    },
    ["Quivioli Ameleonni"] = {
        RoadWeight = 0.425,
        Rarity = "Legendary",
        Generation = 900,
        Price = 225000,
        DisplayName = "Quivioli Ameleonni",
    },
    ["Clickerino Crabo"] = {
        Price = 250000,
        Generation = 1000,
        Rarity = "Legendary",
        DisplayName = "Clickerino Crabo",
    },
    ["Blueberrinni Octopusini"] = {
        RoadWeight = 0.4,
        Rarity = "Legendary",
        Generation = 1000,
        Price = 250000,
        DisplayName = "Blueberrinni Octopusini",
    },
    ["Caramello Filtrello"] = {
        Price = 255000,
        Generation = 1050,
        Rarity = "Legendary",
        DisplayName = "Caramello Filtrello",
    },
    ["Pipi Potato"] = {
        RoadWeight = 0.385,
        Rarity = "Legendary",
        Generation = 1100,
        Price = 265000,
        DisplayName = "Pipi Potato",
    },
    ["Strawberrelli Flamingelli"] = {
        RoadWeight = 0.37,
        Rarity = "Legendary",
        Generation = 1150,
        Price = 275000,
        DisplayName = "Strawberrelli Flamingelli",
    },
    ["Cocosini Mama"] = {
        Price = 285000,
        Generation = 1200,
        Rarity = "Legendary",
        DisplayName = "Cocosini Mama",
    },
    ["Pandaccini Bananini"] = {
        RoadWeight = 0.35,
        Rarity = "Legendary",
        Generation = 1250,
        Price = 300000,
        DisplayName = "Pandaccini Bananini",
    },
    ["Quackula"] = {
        Price = 310000,
        Generation = 1275,
        Rarity = "Legendary",
        DisplayName = "Quackula",
    },
    ["Pi Pi Watermelon"] = {
        Price = 315000,
        Generation = 1300,
        Rarity = "Legendary",
        DisplayName = "Pi Pi Watermelon",
    },
    ["Signore Carapace"] = {
        Price = 320000,
        Generation = 1325,
        Rarity = "Legendary",
        DisplayName = "Signore Carapace",
    },
    ["Sigma Boy"] = {
        RoadWeight = 0.3,
        Rarity = "Legendary",
        Generation = 1350,
        Price = 325000,
        DisplayName = "Sigma Boy",
    },
    ["Sigma Girl"] = {
        Price = 340000,
        Generation = 1800,
        Rarity = "Legendary",
        DisplayName = "Sigma Girl",
    },
    ["Buho de Fuego"] = {
        Price = 345000,
        Generation = 1850,
        Rarity = "Legendary",
        DisplayName = "Buho de Fuego",
    },
    ["Frigo Camelo"] = {
        RoadWeight = 0.2,
        Rarity = "Mythic",
        Generation = 1900,
        Price = 350000,
        DisplayName = "Frigo Camelo",
    },
    ["Orangutini Ananassini"] = {
        RoadWeight = 0.18,
        Rarity = "Mythic",
        Generation = 2000,
        Price = 400000,
        DisplayName = "Orangutini Ananassini",
    },
    ["Rhino Toasterino"] = {
        RoadWeight = 0.16,
        Rarity = "Mythic",
        Generation = 2150,
        Price = 450000,
        DisplayName = "Rhino Toasterino",
    },
    ["Bombardiro Crocodilo"] = {
        RoadWeight = 0.15,
        Rarity = "Mythic",
        Generation = 2500,
        Price = 500000,
        DisplayName = "Bombardiro Crocodilo",
    },
    ["Brutto Gialutto"] = {
        Price = 600000,
        Generation = 3000,
        Rarity = "Mythic",
        DisplayName = "Brutto Gialutto",
    },
    ["Spioniro Golubiro"] = {
        Price = 750000,
        Generation = 3500,
        Rarity = "Mythic",
        DisplayName = "Spioniro Golubiro",
    },
    ["Bombombini Gusini"] = {
        RoadWeight = 0.14,
        Rarity = "Mythic",
        Generation = 5000,
        Price = 1000000,
        DisplayName = "Bombombini Gusini",
    },
    ["Zibra Zubra Zibralini"] = {
        Price = 1500000,
        Generation = 6000,
        Rarity = "Mythic",
        DisplayName = "Zibra Zubra Zibralini",
    },
    ["Tigrilini Watermelini"] = {
        Price = 1750000,
        Generation = 6500,
        Rarity = "Mythic",
        DisplayName = "Tigrilini Watermelini",
    },
    ["Avocadorilla"] = {
        Price = 2000000,
        Generation = 7000,
        Rarity = "Mythic",
        DisplayName = "Avocadorilla",
    },
    ["Cavallo Virtuoso"] = {
        RoadWeight = 0.1,
        Rarity = "Mythic",
        Generation = 7500,
        Price = 2500000,
        DisplayName = "Cavallo Virtuoso",
    },
    ["Gorillo Subwoofero"] = {
        Price = 2750000,
        Generation = 7750,
        Rarity = "Mythic",
        DisplayName = "Gorillo Subwoofero",
    },
    ["Gorillo Watermelondrillo"] = {
        RoadWeight = 0.08,
        Rarity = "Mythic",
        Generation = 8000,
        Price = 3000000,
        DisplayName = "Gorillo Watermelondrillo",
    },
    ["Stoppo Luminino"] = {
        Price = 3000000,
        Generation = 8000,
        Rarity = "Mythic",
        DisplayName = "Stoppo Luminino",
    },
    ["Tob Tobi Tobi"] = {
        Rarity = "Mythic",
        Generation = 8500,
        Price = 3250000,
        IgnoreIndexCounter = true,
        DisplayName = "Tob Tobi Tobi",
    },
    ["Lerulerulerule"] = {
        RoadWeight = 0.75,
        Rarity = "Mythic",
        Generation = 8750,
        Price = 3500000,
        DisplayName = "Lerulerulerule",
    },
    ["Ganganzelli Trulala"] = {
        Rarity = "Mythic",
        Generation = 9000,
        Price = 3750000,
        IgnoreIndexCounter = true,
        DisplayName = "Ganganzelli Trulala",
    },
    ["Te Te Te Sahur"] = {
        RoadWeight = 0.07,
        Rarity = "Mythic",
        Generation = 9500,
        Price = 4000000,
        DisplayName = "Te Te Te Sahur",
    },
    ["Rhino Helicopterino"] = {
        Price = 4100000,
        Generation = 11000,
        Rarity = "Mythic",
        DisplayName = "Rhino Helicopterino",
    },
    ["Magi Ribbitini"] = {
        Price = 4200000,
        Generation = 11500,
        Rarity = "Mythic",
        DisplayName = "Magi Ribbitini",
    },
    ["Tracoducotulu Delapeladustuz"] = {
        RoadWeight = 0.06,
        Rarity = "Mythic",
        Generation = 12000,
        Price = 4250000,
        DisplayName = "Tracoducotulu Delapeladustuz",
    },
    ["Los Noobinis"] = {
        Price = 4350000,
        Generation = 12500,
        Rarity = "Mythic",
        DisplayName = "Los Noobinis",
    },
    ["Cachorrito Melonito"] = {
        RoadWeight = 0.055,
        Rarity = "Mythic",
        Generation = 13000,
        Price = 4400000,
        DisplayName = "Cachorrito Melonito",
    },
    ["Carloo"] = {
        Rarity = "Mythic",
        Generation = 13500,
        Price = 4500000,
        IgnoreIndexCounter = true,
        DisplayName = "Carloo",
    },
    ["Elefanto Frigo"] = {
        Price = 4600000,
        Generation = 14000,
        Rarity = "Mythic",
        DisplayName = "Elefanto Frigo",
    },
    ["Carrotini Brainini"] = {
        Price = 4750000,
        Generation = 15000,
        Rarity = "Mythic",
        DisplayName = "Carrotini Brainini",
    },
    ["Centrucci Nuclucci"] = {
        Price = 4800000,
        Generation = 15500,
        Rarity = "Mythic",
        DisplayName = "Centrucci Nuclucci",
    },
    ["Toiletto Focaccino"] = {
        RoadWeight = 0.05,
        Rarity = "Mythic",
        Generation = 16000,
        Price = 4850000,
        DisplayName = "Toiletto Focaccino",
    },
    ["Jacko Spaventosa"] = {
        Price = 4875000,
        Generation = 16250,
        Rarity = "Mythic",
        DisplayName = "Jacko Spaventosa",
    },
    ["Bananito Bandito"] = {
        Price = 4900000,
        Generation = 16500,
        Rarity = "Mythic",
        DisplayName = "Bananito Bandito",
    },
    ["Cocofanto Elefanto"] = {
        RoadWeight = 0.05,
        Rarity = "Brainrot God",
        Generation = 17500,
        Price = 5000000,
        DisplayName = "Cocofanto Elefanto",
    },
    ["Antonio"] = {
        Price = 6000000,
        Generation = 18500,
        Rarity = "Brainrot God",
        DisplayName = "Antonio",
    },
    ["Girafa Celestre"] = {
        RoadWeight = 0.03,
        Rarity = "Brainrot God",
        Generation = 20000,
        Price = 7500000,
        DisplayName = "Girafa Celestre",
    },
    ["Gattatino Nyanino"] = {
        SpawnVFX = "Gattatino Nyanino",
        Rarity = "Brainrot God",
        Generation = 35000,
        Price = 7500000,
        SpawnDelay = 9,
        IgnoreIndexCounter = true,
        DisplayName = "Gattatino Nyanino",
    },
    ["Chihuanini Taconini"] = {
        SpawnVFX = "Taco",
        Rarity = "Brainrot God",
        Generation = 45000,
        Price = 8500000,
        SpawnDelay = 3,
        IgnoreIndexCounter = true,
        DisplayName = "Chihuanini Taconini",
    },
    ["Matteo"] = {
        SpawnVFX = "Matteo",
        Rarity = "Brainrot God",
        Generation = 50000,
        Price = 10000000,
        SpawnDelay = 3,
        IgnoreIndexCounter = true,
        DisplayName = "Matteo",
    },
    ["Tralalero Tralala"] = {
        RoadWeight = 0.01,
        Rarity = "Brainrot God",
        Generation = 50000,
        Price = 10000000,
        DisplayName = "Tralalero Tralala",
    },
    ["Los Crocodillitos"] = {
        Price = 12500000,
        Generation = 55000,
        Rarity = "Brainrot God",
        DisplayName = "Los Crocodillitos",
    },
    ["Tigroligre Frutonni"] = {
        Price = 14000000,
        Generation = 60000,
        Rarity = "Brainrot God",
        DisplayName = "Tigroligre Frutonni",
    },
    ["Money Money Man"] = {
        Price = 17500000,
        Generation = 65000,
        Rarity = "Brainrot God",
        DisplayName = "Money Money Man",
    },
    ["Espresso Signora"] = {
        Rarity = "Brainrot God",
        Generation = 70000,
        Price = 25000000,
        IgnoreIndexCounter = true,
        DisplayName = "Espresso Signora",
    },
    ["Odin Din Din Dun"] = {
        RoadWeight = 0.007,
        Rarity = "Brainrot God",
        Generation = 75000,
        Price = 15000000,
        DisplayName = "Odin Din Din Dun",
    },
    ["Tipi Topi Taco"] = {
        SpawnVFX = "Taco",
        Rarity = "Brainrot God",
        Generation = 75000,
        Price = 20000000,
        SpawnDelay = 3,
        IgnoreIndexCounter = true,
        DisplayName = "Tipi Topi Taco",
    },
    ["Unclito Samito"] = {
        Rarity = "Brainrot God",
        Generation = 75000,
        Price = 20000000,
        IgnoreIndexCounter = true,
        DisplayName = "Unclito Samito",
    },
    ["Alessio"] = {
        Rarity = "Brainrot God",
        Generation = 85000,
        Price = 17500000,
        IgnoreIndexCounter = true,
        DisplayName = "Alessio",
    },
    ["Tukanno Bananno"] = {
        Rarity = "Brainrot God",
        Generation = 100000,
        Price = 22500000,
        IgnoreIndexCounter = true,
        DisplayName = "Tukanno Bananno",
    },
    ["Tralalita Tralala"] = {
        RoadWeight = 0.006,
        Rarity = "Brainrot God",
        Generation = 100000,
        Price = 20000000,
        DisplayName = "Tralalita Tralala",
    },
    ["Orcalero Orcala"] = {
        Price = 25000000,
        Generation = 100000,
        Rarity = "Brainrot God",
        DisplayName = "Orcalero Orcala",
    },
    ["Vampira Cappucina"] = {
        SpawnVFX = "Witching Hour",
        Rarity = "Brainrot God",
        Generation = 125000,
        Price = 24500000,
        SpawnDelay = 3,
        IgnoreIndexCounter = true,
        DisplayName = "Vampira Cappucina",
    },
    ["Extinct Ballerina"] = {
        SpawnVFX = "Extinct",
        Rarity = "Brainrot God",
        Generation = 125000,
        Price = 23500000,
        SpawnDelay = 3,
        DisplayName = "Extinct Ballerina",
    },
    ["Urubini Flamenguini"] = {
        Rarity = "Brainrot God",
        Generation = 150000,
        Price = 30000000,
        IgnoreIndexCounter = true,
        DisplayName = "Urubini Flamenguini",
    },
    ["Jacko Jack Jack"] = {
        Price = 30000000,
        Generation = 150000,
        Rarity = "Brainrot God",
        DisplayName = "Jacko Jack Jack",
    },
    ["Trenostruzzo Turbo 3000"] = {
        RoadWeight = 0.005,
        Rarity = "Brainrot God",
        Generation = 150000,
        Price = 25000000,
        DisplayName = "Trenostruzzo Turbo 3000",
    },
    ["Capi Taco"] = {
        SpawnVFX = "Taco",
        Rarity = "Brainrot God",
        Generation = 155000,
        Price = 31000000,
        SpawnDelay = 3,
        DisplayName = "Capi Taco",
    },
    ["Los Chihuaninis"] = {
        Rarity = "Brainrot God",
        Generation = 160000,
        Price = 32000000,
        IsEnabled = function: 0xc20d763175d36b38,
        DisplayName = "Los Chihuaninis",
    },
    ["Gattito Tacoto"] = {
        SpawnVFX = "Taco",
        Rarity = "Brainrot God",
        Generation = 165000,
        Price = 32500000,
        SpawnDelay = 3,
        IgnoreIndexCounter = true,
        DisplayName = "Gattito Tacoto",
    },
    ["Trippi Troppi Troppa Trippa"] = {
        RoadWeight = 0.0035,
        Rarity = "Brainrot God",
        Generation = 175000,
        Price = 30000000,
        DisplayName = "Trippi Troppi Troppa Trippa",
    },
    ["Las Capuchinas"] = {
        Price = 32500000,
        Generation = 185000,
        Rarity = "Brainrot God",
        DisplayName = "Las Capuchinas",
    },
    ["Ballerino Lololo"] = {
        RoadWeight = 0.0001,
        Rarity = "Brainrot God",
        Generation = 200000,
        Price = 35000000,
        DisplayName = "Ballerino Lololo",
    },
    ["Bulbito Bandito Traktorito"] = {
        Rarity = "Brainrot God",
        Generation = 205000,
        Price = 35000000,
        IgnoreIndexCounter = true,
        DisplayName = "Bulbito Bandito Traktorito",
    },
    ["Los Tungtungtungcitos"] = {
        Rarity = "Brainrot God",
        Generation = 210000,
        Price = 37500000,
        IgnoreIndexCounter = true,
        DisplayName = "Los Tungtungtungcitos",
    },
    ["Pakrahmatmamat"] = {
        RoadWeight = 0.0009,
        Rarity = "Brainrot God",
        Generation = 215000,
        Price = 37500000,
        DisplayName = "Pakrahmatmamat",
    },
    ["Los Bombinitos"] = {
        Rarity = "Brainrot God",
        Generation = 220000,
        Price = 42500000,
        IgnoreIndexCounter = true,
        DisplayName = "Los Bombinitos",
    },
    ["Brr es Teh Patipum"] = {
        Rarity = "Brainrot God",
        Generation = 225000,
        Price = 40000000,
        IgnoreIndexCounter = true,
        DisplayName = "Brr es Teh Patipum",
    },
    ["Pakrahmatmatina"] = {
        Price = 40500000,
        Generation = 225000,
        Rarity = "Brainrot God",
        DisplayName = "Pakrahmatmatina",
    },
    ["Bombardini Tortinii"] = {
        SpawnVFX = "Taco",
        Rarity = "Brainrot God",
        Generation = 225000,
        Price = 50000000,
        SpawnDelay = 3,
        IgnoreIndexCounter = true,
        DisplayName = "Bombardini Tortinii",
    },
    ["Piccione Macchina"] = {
        RoadWeight = 0.0008,
        Rarity = "Brainrot God",
        Generation = 225000,
        Price = 40000000,
        DisplayName = "Piccione Macchina",
    },
    ["Tractoro Dinosauro"] = {
        RoadWeight = 0.00065,
        Rarity = "Brainrot God",
        Generation = 230000,
        Price = 42500000,
        DisplayName = "Tractoro Dinosauro",
    },
    ["Los Orcalitos"] = {
        Rarity = "Brainrot God",
        Generation = 235000,
        Price = 45000000,
        IgnoreIndexCounter = true,
        DisplayName = "Los Orcalitos",
    },
    ["Crabbo Limonetta"] = {
        Rarity = "Brainrot God",
        Generation = 235000,
        Price = 46000000,
        IgnoreIndexCounter = true,
        DisplayName = "Crabbo Limonetta",
    },
    ["Orcalita Orcala"] = {
        Price = 45000000,
        Generation = 240000,
        Rarity = "Brainrot God",
        DisplayName = "Orcalita Orcala",
    },
    ["Cacasito Satalito"] = {
        RoadWeight = 0.0006,
        Rarity = "Brainrot God",
        Generation = 240000,
        Price = 45000000,
        DisplayName = "Cacasito Satalito",
    },
    ["Aquanaut"] = {
        RoadWeight = 0.00055,
        Rarity = "Brainrot God",
        Generation = 245000,
        Price = 45500000,
        DisplayName = "Aquanaut",
    },
    ["Tartaruga Cisterna"] = {
        Price = 45000000,
        Generation = 250000,
        Rarity = "Brainrot God",
        DisplayName = "Tartaruga Cisterna",
    },
    ["Corn Corn Corn Sahur"] = {
        Price = 45000000,
        Generation = 250000,
        Rarity = "Brainrot God",
        DisplayName = "Corn Corn Corn Sahur",
    },
    ["Squalanana"] = {
        Price = 45000000,
        Generation = 250000,
        Rarity = "Brainrot God",
        DisplayName = "Squalanana",
    },
    ["Snailenzo"] = {
        Price = 45000000,
        Generation = 250000,
        Rarity = "Brainrot God",
        DisplayName = "Snailenzo",
    },
    ["Mummy Ambalabu"] = {
        Price = 45000000,
        Generation = 250000,
        Rarity = "Brainrot God",
        DisplayName = "Mummy Ambalabu",
    },
    ["Dug dug dug"] = {
        Price = 45500000,
        Generation = 255000,
        Rarity = "Brainrot God",
        DisplayName = "Dug dug dug",
    },
    ["Los Tipi Tacos"] = {
        SpawnVFX = "Taco",
        Rarity = "Brainrot God",
        Generation = 260000,
        Price = 46000000,
        SpawnDelay = 3,
        IgnoreIndexCounter = true,
        DisplayName = "Los Tipi Tacos",
    },
    ["Frio Ninja"] = {
        Price = 46500000,
        Generation = 265000,
        Rarity = "Brainrot God",
        DisplayName = "Frio Ninja",
    },
    ["Piccionetta Macchina"] = {
        Price = 47000000,
        Generation = 270000,
        Rarity = "Brainrot God",
        DisplayName = "Piccionetta Macchina",
    },
    ["Mastodontico Telepiedone"] = {
        Price = 47500000,
        Generation = 275000,
        Rarity = "Brainrot God",
        DisplayName = "Mastodontico Telepiedone",
    },
    ["Los Gattitos"] = {
        Rarity = "Brainrot God",
        Generation = 275000,
        Price = 47500000,
        IsEnabled = function: 0x287bb2232ec45ec8,
        DisplayName = "Los Gattitos",
    },
    ["Bambu Bambu Sahur"] = {
        Price = 47500000,
        Generation = 275000,
        Rarity = "Brainrot God",
        DisplayName = "Bambu Bambu Sahur",
    },
    ["Noo La Polizia"] = {
        Price = 67000000,
        Generation = 280000,
        Rarity = "Brainrot God",
        DisplayName = "Noo La Polizia",
    },
    ["Anpali Babel"] = {
        Price = 48000000,
        Generation = 280000,
        Rarity = "Brainrot God",
        DisplayName = "Anpali Babel",
    },
    ["Brasilini Berimbini"] = {
        Rarity = "Brainrot God",
        Generation = 285000,
        Price = 55000000,
        IgnoreIndexCounter = true,
        DisplayName = "Brasilini Berimbini",
    },
    ["Cappuccino Clownino"] = {
        Price = 48500000,
        Generation = 285000,
        Rarity = "Brainrot God",
        DisplayName = "Cappuccino Clownino",
    },
    ["Skull Skull Skull"] = {
        Price = 60000000,
        Generation = 290000,
        Rarity = "Brainrot God",
        DisplayName = "Skull Skull Skull",
    },
    ["Krupuk Pagi Pagi"] = {
        Price = 60000000,
        Generation = 290000,
        Rarity = "Brainrot God",
        DisplayName = "Krupuk Pagi Pagi",
    },
    ["Belula Beluga"] = {
        Price = 60000000,
        Generation = 290000,
        Rarity = "Brainrot God",
        DisplayName = "Belula Beluga",
    },
    ["Tentacolo Tecnico"] = {
        Price = 62500000,
        Generation = 292500,
        Rarity = "Brainrot God",
        DisplayName = "Tentacolo Tecnico",
    },
    ["Pop Pop Sahur"] = {
        Price = 65000000,
        Generation = 295000,
        Rarity = "Brainrot God",
        DisplayName = "Pop Pop Sahur",
    },
    ["Los Matteos"] = {
        SpawnVFX = "Matteo",
        Rarity = "Secret",
        Generation = 300000,
        Price = 100000000,
        SpawnDelay = 3,
        IgnoreIndexCounter = true,
        DisplayName = "Los Matteos",
    },
    ["La Vacca Saturno Saturnita"] = {
        RoadWeight = 0.0005,
        Rarity = "Secret",
        Generation = 300000,
        Price = 50000000,
        DisplayName = "La Vacca Saturno Saturnita",
    },
    ["Karkerkar Kurkur"] = {
        SpawnVFX = "Karkerkar Kurkur",
        Rarity = "Secret",
        Generation = 300000,
        Price = 100000000,
        SpawnDelay = 3,
        IgnoreIndexCounter = true,
        DisplayName = "Karkerkar Kurkur",
    },
    ["Bisonte Giuppitere"] = {
        Rarity = "Secret",
        Generation = 300000,
        Price = 75000000,
        IgnoreIndexCounter = true,
        DisplayName = "Bisonte Giuppitere",
    },
    ["Trenostruzzo Turbo 4000"] = {
        Price = 100000000,
        Generation = 310000,
        Rarity = "Secret",
        DisplayName = "Trenostruzzo Turbo 4000",
    },
    ["Jackorilla"] = {
        Price = 80000000,
        Generation = 315000,
        Rarity = "Secret",
        DisplayName = "Jackorilla",
    },
    ["Sammyni Spyderini"] = {
        SpawnVFX = "Los Spyderinis",
        Rarity = "Secret",
        Generation = 325000,
        Price = 75000000,
        SpawnDelay = 3.5,
        IgnoreIndexCounter = true,
        DisplayName = "Sammyni Spyderini",
    },
    ["Torrtuginni Dragonfrutini"] = {
        Price = 125000000,
        Generation = 350000,
        Rarity = "Secret",
        DisplayName = "Torrtuginni Dragonfrutini",
    },
    ["Dul Dul Dul"] = {
        Rarity = "Secret",
        Generation = 375000,
        Price = 150000000,
        IgnoreIndexCounter = true,
        DisplayName = "Dul Dul Dul",
    },
    ["Chachechi"] = {
        Price = 85000000,
        Generation = 400000,
        Rarity = "Secret",
        DisplayName = "Chachechi",
    },
    ["Blackhole Goat"] = {
        Rarity = "Secret",
        Generation = 400000,
        Price = 75000000,
        IgnoreIndexCounter = true,
        DisplayName = "Blackhole Goat",
    },
    ["Los Spyderinis"] = {
        SpawnVFX = "Los Spyderinis",
        Rarity = "Secret",
        Generation = 425000,
        Price = 125000000,
        SpawnDelay = 3.5,
        IgnoreIndexCounter = true,
        DisplayName = "Los Spyderinis",
    },
    ["Agarrini la Palini"] = {
        Rarity = "Secret",
        Generation = 425000,
        Price = 80000000,
        IgnoreIndexCounter = true,
        DisplayName = "Agarrini la Palini",
    },
    ["Extinct Tralalero"] = {
        SpawnVFX = "Extinct",
        Rarity = "Secret",
        Generation = 450000,
        Price = 125000000,
        SpawnDelay = 3,
        DisplayName = "Extinct Tralalero",
    },
    ["Fragola La La La"] = {
        Price = 125000000,
        Generation = 450000,
        Rarity = "Secret",
        DisplayName = "Fragola La La La",
    },
    ["La Cucaracha"] = {
        SpawnVFX = "Mexico",
        Rarity = "Secret",
        Generation = 475000,
        Price = 110000000,
        SpawnDelay = 3.5,
        IgnoreIndexCounter = true,
        DisplayName = "La Cucaracha",
    },
    ["Los Tralaleritos"] = {
        RoadWeight = 0.0001,
        Rarity = "Secret",
        Generation = 500000,
        Price = 100000000,
        DisplayName = "Los Tralaleritos",
    },
    ["Los Tortus"] = {
        Price = 100000000,
        Generation = 500000,
        Rarity = "Secret",
        DisplayName = "Los Tortus",
    },
    ["Vulturino Skeletono"] = {
        Price = 110000000,
        Generation = 500000,
        Rarity = "Secret",
        DisplayName = "Vulturino Skeletono",
    },
    ["Zombie Tralala"] = {
        SpawnVFX = "Witching Hour",
        Rarity = "Secret",
        Generation = 500000,
        Price = 100000000,
        SpawnDelay = 3,
        IgnoreIndexCounter = true,
        DisplayName = "Zombie Tralala",
    },
    ["Boatito Auratito"] = {
        SpawnVFX = "Indonesia",
        Rarity = "Secret",
        Generation = 525000,
        Price = 115000000,
        SpawnDelay = 3.5,
        IgnoreIndexCounter = true,
        DisplayName = "Boatito Auratito",
    },
    ["Guerriro Digitale"] = {
        Rarity = "Secret",
        Generation = 550000,
        Price = 120000000,
        IgnoreIndexCounter = true,
        DisplayName = "Guerriro Digitale",
    },
    ["Yess my examine"] = {
        Price = 130000000,
        Generation = 575000,
        Rarity = "Secret",
        DisplayName = "Yess my examine",
    },
    ["La Karkerkar Combinasion"] = {
        Rarity = "Secret",
        Generation = 600000,
        Price = 160000000,
        IgnoreIndexCounter = true,
        DisplayName = "La Karkerkar Combinasion",
    },
    ["Extinct Matteo"] = {
        SpawnVFX = "Extinct",
        Rarity = "Secret",
        Generation = 625000,
        Price = 140000000,
        SpawnDelay = 3,
        DisplayName = "Extinct Matteo",
    },
    ["Las Tralaleritas"] = {
        RoadWeight = 0.00007,
        Rarity = "Secret",
        Generation = 650000,
        Price = 150000000,
        DisplayName = "Las Tralaleritas",
    },
    ["Pumpkini Spyderini"] = {
        Price = 165000000,
        Generation = 650000,
        Rarity = "Secret",
        DisplayName = "Pumpkini Spyderini",
    },
    ["Job Job Job Sahur"] = {
        RoadWeight = 0.000005,
        Rarity = "Secret",
        Generation = 700000,
        Price = 175000000,
        DisplayName = "Job Job Job Sahur",
    },
    ["Frankentteo"] = {
        SpawnVFX = "Witching Hour",
        Rarity = "Secret",
        Generation = 700000,
        Price = 175000000,
        SpawnDelay = 3,
        IgnoreIndexCounter = true,
        DisplayName = "Frankentteo",
    },
    ["Karker Sahur"] = {
        Price = 185000000,
        Generation = 725000,
        Rarity = "Secret",
        DisplayName = "Karker Sahur",
    },
    ["Los Karkeritos"] = {
        SpawnVFX = "Karkerkar Kurkur",
        Rarity = "Secret",
        Generation = 750000,
        Price = 200000000,
        SpawnDelay = 3,
        DisplayName = "Los Karkeritos",
    },
    ["Las Vaquitas Saturnitas"] = {
        Price = 200000000,
        Generation = 750000,
        Rarity = "Secret",
        DisplayName = "Las Vaquitas Saturnitas",
    },
    ["La Vacca Jacko Linterino"] = {
        SpawnVFX = "Witching Hour",
        Rarity = "Secret",
        Generation = 850000,
        Price = 225000000,
        SpawnDelay = 3,
        IgnoreIndexCounter = true,
        DisplayName = "La Vacca Jacko Linterino",
    },
    ["Trickolino"] = {
        Price = 235000000,
        Generation = 900000,
        Rarity = "Secret",
        DisplayName = "Trickolino",
    },
    ["Perrito Burrito"] = {
        SpawnVFX = "Taco",
        Rarity = "Secret",
        Generation = 1000000,
        Price = 250000000,
        SpawnDelay = 3,
        IgnoreIndexCounter = true,
        DisplayName = "Perrito Burrito",
    },
    ["Graipuss Medussi"] = {
        RoadWeight = 0.000001,
        Rarity = "Secret",
        Generation = 1000000,
        Price = 250000000,
        DisplayName = "Graipuss Medussi",
    },
    ["1x1x1x1"] = {
        Price = 255555555,
        Generation = 1111111,
        Rarity = "Secret",
        DisplayName = "1x1x1x1",
    },
    ["Los Cucarachas"] = {
        Rarity = "Secret",
        Generation = 1250000,
        Price = 300000000,
        IsEnabled = function: 0xf7335f5b20f3e4b8,
        DisplayName = "Los Cucarachas",
    },
    ["Nooo My Hotspot"] = {
        SpawnVFX = "Taco",
        Rarity = "Secret",
        Generation = 1500000,
        Price = 500000000,
        SpawnDelay = 3,
        IgnoreIndexCounter = true,
        DisplayName = "Nooo My Hotspot",
    },
    ["Los Jobcitos"] = {
        Price = 500000000,
        Generation = 1500000,
        Rarity = "Secret",
        DisplayName = "Los Jobcitos",
    },
    ["Noo my examine"] = {
        Rarity = "Secret",
        Generation = 1750000,
        Price = 525000000,
        IgnoreIndexCounter = true,
        DisplayName = "Noo my examine",
    },
    ["Telemorte"] = {
        Price = 550000000,
        Generation = 2000000,
        Rarity = "Secret",
        DisplayName = "Telemorte",
    },
    ["La Sahur Combinasion"] = {
        Price = 550000000,
        Generation = 2000000,
        Rarity = "Secret",
        DisplayName = "La Sahur Combinasion",
    },
    ["To to to Sahur"] = {
        RoadWeight = 5e-07,
        Rarity = "Secret",
        Generation = 2250000,
        Price = 575000000,
        DisplayName = "To to to Sahur",
    },
    ["Pot Hotspot"] = {
        Price = 600000000,
        Generation = 2500000,
        Rarity = "Secret",
        DisplayName = "Pot Hotspot",
    },
    ["Pirulitoita Bicicleteira"] = {
        Price = 600000000,
        Generation = 2500000,
        Rarity = "Secret",
        DisplayName = "Pirulitoita Bicicleteira",
    },
    ["Horegini Boom"] = {
        Price = 650000000,
        Generation = 2750000,
        Rarity = "Secret",
        DisplayName = "Horegini Boom",
    },
    ["Pot Pumpkin"] = {
        Price = 700000000,
        Generation = 3000000,
        Rarity = "Secret",
        DisplayName = "Pot Pumpkin",
    },
    ["Quesadilla Crocodila"] = {
        SpawnVFX = "Taco",
        Rarity = "Secret",
        Generation = 3000000,
        Price = 700000000,
        SpawnDelay = 3,
        DisplayName = "Quesadilla Crocodila",
    },
    ["Chicleteira Bicicleteira"] = {
        RoadWeight = 1e-07,
        Rarity = "Secret",
        Generation = 3500000,
        Price = 750000000,
        DisplayName = "Chicleteira Bicicleteira",
    },
    ["Quesadillo Vampiro"] = {
        SpawnVFX = "Taco",
        Rarity = "Secret",
        Generation = 3500000,
        Price = 750000000,
        SpawnDelay = 3,
        DisplayName = "Quesadillo Vampiro",
    },
    ["Chicleteirina Bicicleteirina"] = {
        RoadWeight = 5e-08,
        Rarity = "Secret",
        Generation = 4000000,
        Price = 850000000,
        DisplayName = "Chicleteirina Bicicleteirina",
    },
    ["Burrito Bandito"] = {
        SpawnVFX = "Taco",
        Rarity = "Secret",
        Generation = 4000000,
        Price = 850000000,
        SpawnDelay = 3,
        DisplayName = "Burrito Bandito",
    },
    ["Los Quesadillas"] = {
        Rarity = "Secret",
        Generation = 4500000,
        Price = 875000000,
        IsEnabled = function: 0x639cd15e0e37e858,
        DisplayName = "Los Quesadillas",
    },
    ["Noo my Candy"] = {
        Price = 900000000,
        Generation = 5000000,
        Rarity = "Secret",
        DisplayName = "Noo my Candy",
    },
    ["Los Nooo My Hotspotsitos"] = {
        SpawnVFX = "Taco",
        Rarity = "Secret",
        Generation = 5500000,
        Price = 1000000000,
        SpawnDelay = 3,
        IgnoreIndexCounter = true,
        DisplayName = "Los Nooo My Hotspotsitos",
    },
    ["Rang Ring Bus"] = {
        Price = 1100000000,
        Generation = 6000000,
        Rarity = "Secret",
        DisplayName = "Rang Ring Bus",
    },
    ["Guest 666"] = {
        Price = 1166666666,
        Generation = 6666666,
        Rarity = "Secret",
        DisplayName = "Guest 666",
    },
    ["Los Chicleteiras"] = {
        SpawnVFX = "Los Chicleteiras",
        Rarity = "Secret",
        Generation = 7000000,
        Price = 1200000000,
        SpawnDelay = 3,
        DisplayName = "Los Chicleteiras",
    },
    ["67"] = {
        Price = 1250000000,
        Generation = 7500000,
        Rarity = "Secret",
        DisplayName = "67",
    },
    ["Los Burritos"] = {
        Rarity = "Secret",
        Generation = 8500000,
        Price = 1400000000,
        IsEnabled = function: 0xb9e99341f5e1fe48,
        DisplayName = "Los Burritos",
    },
    ["La Grande Combinasion"] = {
        RoadWeight = 1e-08,
        Rarity = "Secret",
        Generation = 10000000,
        OverheadYOffsetModifier = 0.8,
        Price = 1000000000,
        DisplayName = "La Grande Combinasion",
    },
    ["Mariachi Corazoni"] = {
        Rarity = "Secret",
        Generation = 12500000,
        Price = 1750000000,
        IgnoreIndexCounter = true,
        DisplayName = "Mariachi Corazoni",
    },
    ["Swag Soda"] = {
        Price = 1800000000,
        Generation = 13000000,
        Rarity = "Secret",
        DisplayName = "Swag Soda",
    },
    ["Nuclearo Dinossauro"] = {
        RoadWeight = 1e-10,
        Rarity = "Secret",
        Generation = 15000000,
        Price = 2500000000,
        DisplayName = "Nuclearo Dinossauro",
    },
    ["Los Combinasionas"] = {
        Rarity = "Secret",
        Generation = 15000000,
        Price = 2000000000,
        IgnoreIndexCounter = true,
        DisplayName = "Los Combinasionas",
    },
    ["Tacorita Bicicleta"] = {
        SpawnVFX = "Taco",
        Rarity = "Secret",
        Generation = 16500000,
        Price = 2250000000,
        SpawnDelay = 3,
        DisplayName = "Tacorita Bicicleta",
    },
    ["Las Sis"] = {
        Price = 2500000000,
        Generation = 17500000,
        Rarity = "Secret",
        DisplayName = "Las Sis",
    },
    ["Los Hotspotsitos"] = {
        Rarity = "Secret",
        Generation = 20000000,
        Price = 3000000000,
        IgnoreIndexCounter = true,
        DisplayName = "Los Hotspotsitos",
    },
    ["Los Spooky Combinasionas"] = {
        Price = 3000000000,
        Generation = 20000000,
        Rarity = "Secret",
        DisplayName = "Los Spooky Combinasionas",
    },
    ["Money Money Puggy"] = {
        RoadWeight = 5e-10,
        Rarity = "Secret",
        Generation = 21000000,
        Price = 2600000000,
        DisplayName = "Money Money Puggy",
    },
    ["Los Mobilis"] = {
        Price = 2700000000,
        Generation = 22000000,
        Rarity = "Secret",
        DisplayName = "Los Mobilis",
    },
    ["Los 67"] = {
        Price = 2750000000,
        Generation = 22500000,
        Rarity = "Secret",
        DisplayName = "Los 67",
    },
    ["Celularcini Viciosini"] = {
        Price = 2750000000,
        Generation = 22500000,
        Rarity = "Secret",
        DisplayName = "Celularcini Viciosini",
    },
    ["La Extinct Grande"] = {
        SpawnVFX = "Extinct",
        Rarity = "Secret",
        Generation = 23500000,
        Price = 3250000000,
        SpawnDelay = 3,
        IgnoreIndexCounter = true,
        DisplayName = "La Extinct Grande",
    },
    ["Los Bros"] = {
        Price = 2600000000,
        Generation = 24000000,
        Rarity = "Secret",
        DisplayName = "Los Bros",
    },
    ["La Spooky Grande"] = {
        SpawnVFX = "Witching Hour",
        Rarity = "Secret",
        Generation = 24500000,
        Price = 2900000000,
        SpawnDelay = 3,
        IgnoreIndexCounter = true,
        DisplayName = "La Spooky Grande",
    },
    ["Chillin Chili"] = {
        SpawnVFX = "Taco",
        Rarity = "Secret",
        Generation = 25000000,
        Price = 2500000000,
        SpawnDelay = 3,
        IgnoreIndexCounter = true,
        DisplayName = "Chillin Chili",
    },
    ["Chipso and Queso"] = {
        SpawnVFX = "Taco",
        Rarity = "Secret",
        Generation = 25000000,
        Price = 2500000000,
        SpawnDelay = 3,
        DisplayName = "Chipso and Queso",
    },
    ["Mieteteira Bicicleteira"] = {
        Price = 2750000000,
        Generation = 26000000,
        Rarity = "Secret",
        DisplayName = "Mieteteira Bicicleteira",
    },
    ["Tralaledon"] = {
        Price = 3000000000,
        Generation = 27500000,
        Rarity = "Secret",
        DisplayName = "Tralaledon",
    },
    ["Los Puggies"] = {
        Price = 3000000000,
        Generation = 30000000,
        Rarity = "Secret",
        DisplayName = "Los Puggies",
    },
    ["Esok Sekolah"] = {
        Rarity = "Secret",
        Generation = 30000000,
        Price = 3500000000,
        IgnoreIndexCounter = true,
        DisplayName = "Esok Sekolah",
    },
    ["Los Primos"] = {
        Price = 3750000000,
        Generation = 31000000,
        Rarity = "Secret",
        DisplayName = "Los Primos",
    },
    ["Eviledon"] = {
        Price = 3850000000,
        Generation = 31500000,
        Rarity = "Secret",
        DisplayName = "Eviledon",
    },
    ["Los Tacoritas"] = {
        Price = 4000000000,
        Generation = 32000000,
        Rarity = "Secret",
        DisplayName = "Los Tacoritas",
    },
    ["Tang Tang Keletang"] = {
        RoadWeight = 7.5e-11,
        Rarity = "Secret",
        Generation = 33500000,
        Price = 4500000000,
        IgnoreIndexCounter = true,
        DisplayName = "Tang Tang Keletang",
    },
    ["Ketupat Kepat"] = {
        RoadWeight = 5e-11,
        Rarity = "Secret",
        Generation = 35000000,
        Price = 5000000000,
        DisplayName = "Ketupat Kepat",
    },
    ["La Taco Combinasion"] = {
        SpawnVFX = "Taco",
        Rarity = "Secret",
        Generation = 35000000,
        Price = 5000000000,
        SpawnDelay = 3,
        DisplayName = "La Taco Combinasion",
    },
    ["Tictac Sahur"] = {
        RoadWeight = 3.5e-11,
        Rarity = "Secret",
        Generation = 37500000,
        Price = 6000000000,
        DisplayName = "Tictac Sahur",
    },
    ["Orcaledon"] = {
        Price = 7000000000,
        Generation = 40000000,
        Rarity = "Secret",
        DisplayName = "Orcaledon",
    },
    ["La Supreme Combinasion"] = {
        Rarity = "Secret",
        Generation = 40000000,
        Price = 7000000000,
        IgnoreIndexCounter = true,
        DisplayName = "La Supreme Combinasion",
    },
    ["Ketchuru and Musturu"] = {
        RoadWeight = 2.5e-11,
        Rarity = "Secret",
        Generation = 42500000,
        Price = 7500000000,
        DisplayName = "Ketchuru and Musturu",
    },
    ["Garama and Madundung"] = {
        RoadWeight = 1e-10,
        Rarity = "Secret",
        Generation = 50000000,
        Price = 10000000000,
        DisplayName = "Garama and Madundung",
    },
    ["Spaghetti Tualetti"] = {
        Price = 15000000000,
        Generation = 60000000,
        Rarity = "Secret",
        DisplayName = "Spaghetti Tualetti",
    },
    ["Los Spaghettis"] = {
        Price = 20000000000,
        Generation = 70000000,
        Rarity = "Secret",
        DisplayName = "Los Spaghettis",
    },
    ["Spooky and Pumpky"] = {
        Price = 25000000000,
        Generation = 80000000,
        Rarity = "Secret",
        DisplayName = "Spooky and Pumpky",
    },
    ["Fragrama and Chocrama"] = {
        Price = 40000000000,
        Generation = 100000000,
        Rarity = "Secret",
        DisplayName = "Fragrama and Chocrama",
    },
    ["La Casa Boo"] = {
        Price = 40000000000,
        Generation = 100000000,
        Rarity = "Secret",
        DisplayName = "La Casa Boo",
    },
    ["La Secret Combinasion"] = {
        Price = 50000000000,
        Generation = 125000000,
        Rarity = "Secret",
        DisplayName = "La Secret Combinasion",
    },
    ["Burguro And Fryuro"] = {
        RoadWeight = 5e-13,
        Rarity = "Secret",
        Generation = 150000000,
        Price = 75000000000,
        DisplayName = "Burguro And Fryuro",
    },
    ["Capitano Moby"] = {
        RoadWeight = 1e-13,
        Rarity = "Secret",
        Generation = 160000000,
        Price = 125000000000,
        DisplayName = "Capitano Moby",
    },
    ["Headless Horseman"] = {
        Price = 150000000000,
        Generation = 175000000,
        Rarity = "Secret",
        DisplayName = "Headless Horseman",
    },
    ["Dragon Cannelloni"] = {
        RoadWeight = 5e-14,
        Rarity = "Secret",
        Generation = 250000000,
        Price = 250000000000,
        DisplayName = "Dragon Cannelloni",
    },
    ["Meowl"] = {
        TriggerEvent = "Meowl",
        SpawnVFX = "Meowl",
        Rarity = "OG",
        Generation = 400000000,
        Price = 400000000000,
        SpawnDelay = 3.5,
        IgnoreIndexCounter = true,
        DisplayName = "Meowl",
    },
    ["Strawberry Elephant"] = {
        TriggerEvent = "Strawberry",
        SpawnVFX = "Strawberry",
        Rarity = "OG",
        Generation = 500000000,
        Price = 500000000000,
        SpawnDelay = 3.5,
        IgnoreIndexCounter = true,
        DisplayName = "Strawberry Elephant",
    },
}
return v7
