local v7 = {
    ["Noobini Pizzanini"] = {
        Name = "Noobini Pizzanini",
        DisplayName = "Noobini Pizzanini",
        Rarity = "Common",
        Price = 25,
        Generation = 1,
    },
    ["Lirilì Larilà"] = {
        Name = "Lirilì Larilà",
        DisplayName = "Lirilì Larilà",
        Rarity = "Common",
        Price = 250,
        Generation = 3,
    },
    ["Tim Cheese"] = {
        Name = "Tim Cheese",
        DisplayName = "Tim Cheese",
        Rarity = "Common",
        Price = 500,
        Generation = 5,
    },
    ["Fluriflura"] = {
        Name = "Fluriflura",
        DisplayName = "Fluriflura",
        Rarity = "Common",
        Price = 750,
        Generation = 7,
    },
    ["Talpa Di Fero"] = {
        Name = "Talpa Di Fero",
        DisplayName = "Talpa Di Fero",
        Rarity = "Common",
        Price = 1000,
        Generation = 9,
    },
    ["Svinina Bombardino"] = {
        Name = "Svinina Bombardino",
        DisplayName = "Svinina Bombardino",
        Rarity = "Common",
        Price = 1250,
        Generation = 10,
    },
    ["Raccooni Jandelini"] = {
        Name = "Raccooni Jandelini",
        DisplayName = "Raccooni Jandelini",
        Rarity = "Common",
        Price = 1350,
        Generation = 12,
    },
    ["Pipi Kiwi"] = {
        Name = "Pipi Kiwi",
        DisplayName = "Pipi Kiwi",
        Rarity = "Common",
        Price = 1500,
        Generation = 13,
    },
    ["Tartaragno"] = {
        Name = "Tartaragno",
        DisplayName = "Tartaragno",
        Rarity = "Common",
        Price = 1500,
        Generation = 13,
    },
    ["Pipi Corni"] = {
        Name = "Pipi Corni",
        DisplayName = "Pipi Corni",
        Rarity = "Common",
        Price = 1750,
        Generation = 14,
    },
    ["Trippi Troppi"] = {
        Name = "Trippi Troppi",
        DisplayName = "Trippi Troppi",
        Rarity = "Rare",
        Price = 2000,
        Generation = 15,
    },
    ["Gangster Footera"] = {
        Name = "Gangster Footera",
        DisplayName = "Gangster Footera",
        Rarity = "Rare",
        Price = 4000,
        Generation = 30,
    },
    ["Bandito Bobritto"] = {
        Name = "Bandito Bobritto",
        DisplayName = "Bandito Bobritto",
        Rarity = "Rare",
        Price = 4500,
        Generation = 35,
    },
    ["Boneca Ambalabu"] = {
        Name = "Boneca Ambalabu",
        DisplayName = "Boneca Ambalabu",
        Rarity = "Rare",
        Price = 5000,
        Generation = 40,
    },
    ["Cacto Hipopotamo"] = {
        Name = "Cacto Hipopotamo",
        DisplayName = "Cacto Hipopotamo",
        Rarity = "Rare",
        Price = 6500,
        Generation = 50,
    },
    ["Ta Ta Ta Ta Sahur"] = {
        Name = "Ta Ta Ta Ta Sahur",
        DisplayName = "Ta Ta Ta Ta Sahur",
        Rarity = "Rare",
        Price = 7500,
        Generation = 55,
    },
    ["Cupcake Koala"] = {
        Name = "Cupcake Koala",
        DisplayName = "Cupcake Koala",
        Rarity = "Rare",
        Price = 8000,
        Generation = 60,
    },
    ["Tric Trac Baraboom"] = {
        Name = "Tric Trac Baraboom",
        DisplayName = "Tric Trac Baraboom",
        Rarity = "Rare",
        Price = 9000,
        Generation = 65,
    },
    ["Pipi Avocado"] = {
        Name = "Pipi Avocado",
        DisplayName = "Pipi Avocado",
        Rarity = "Rare",
        Price = 9500,
        Generation = 70,
    },
    ["Pinealotto Fruttarino"] = {
        Name = "Pinealotto Fruttarino",
        DisplayName = "Pinealotto Fruttarino",
        Rarity = "Rare",
        Price = 9750,
        Generation = 75,
    },
    ["Cappuccino Assassino"] = {
        Name = "Cappuccino Assassino",
        DisplayName = "Cappuccino Assassino",
        Rarity = "Epic",
        Price = 10000,
        Generation = 75,
    },
    ["Bandito Axolito"] = {
        Name = "Bandito Axolito",
        DisplayName = "Bandito Axolito",
        Rarity = "Epic",
        Price = 12500,
        Generation = 90,
    },
    ["Brr Brr Patapim"] = {
        Name = "Brr Brr Patapim",
        DisplayName = "Brr Brr Patapim",
        Rarity = "Epic",
        Price = 15000,
        Generation = 100,
    },
    ["Avocadini Antilopini"] = {
        Name = "Avocadini Antilopini",
        DisplayName = "Avocadini Antilopini",
        Rarity = "Epic",
        Price = 17500,
        Generation = 115,
    },
    ["Trulimero Trulicina"] = {
        Name = "Trulimero Trulicina",
        DisplayName = "Trulimero Trulicina",
        Rarity = "Epic",
        Price = 20000,
        Generation = 125,
    },
    ["Bambini Crostini"] = {
        Name = "Bambini Crostini",
        DisplayName = "Bambini Crostini",
        Rarity = "Epic",
        Price = 22500,
        Generation = 135,
    },
    ["Malame Amarele"] = {
        Name = "Malame Amarele",
        DisplayName = "Malame Amarele",
        Rarity = "Epic",
        Price = 23500,
        Generation = 140,
    },
    ["Bananita Dolphinita"] = {
        Name = "Bananita Dolphinita",
        DisplayName = "Bananita Dolphinita",
        Rarity = "Epic",
        Price = 25000,
        Generation = 150,
    },
    ["Perochello Lemonchello"] = {
        Name = "Perochello Lemonchello",
        DisplayName = "Perochello Lemonchello",
        Rarity = "Epic",
        Price = 27500,
        Generation = 160,
    },
    ["Brri Brri Bicus Dicus Bombicus"] = {
        Name = "Brri Brri Bicus Dicus Bombicus",
        DisplayName = "Brri Brri Bicus Dicus Bombicus",
        Rarity = "Epic",
        Price = 30000,
        Generation = 175,
    },
    ["Avocadini Guffo"] = {
        Name = "Avocadini Guffo",
        DisplayName = "Avocadini Guffo",
        Rarity = "Epic",
        Price = 35000,
        Generation = 225,
    },
    ["Burbaloni Loliloli"] = {
        Name = "Burbaloni Loliloli",
        DisplayName = "Burbaloni Loliloli",
        Rarity = "Legendary",
        Price = 35000,
        Generation = 200,
    },
    ["Ti Ti Ti Sahur"] = {
        Name = "Ti Ti Ti Sahur",
        DisplayName = "Ti Ti Ti Sahur",
        Rarity = "Epic",
        Price = 37500,
        Generation = 225,
    },
    ["Mangolini Parrocini"] = {
        Name = "Mangolini Parrocini",
        DisplayName = "Mangolini Parrocini",
        Rarity = "Epic",
        Price = 38500,
        Generation = 235,
    },
    ["Frogato Pirato"] = {
        Name = "Frogato Pirato",
        DisplayName = "Frogato Pirato",
        Rarity = "Epic",
        Price = 39000,
        Generation = 240,
    },
    ["Salamino Penguino"] = {
        Name = "Salamino Penguino",
        DisplayName = "Salamino Penguino",
        Rarity = "Epic",
        Price = 40000,
        Generation = 250,
    },
    ["Doi Doi Do"] = {
        Name = "Doi Doi Do",
        DisplayName = "Doi Doi Do",
        Rarity = "Epic",
        Price = 41000,
        Generation = 260,
    },
    ["Wombo Rollo"] = {
        Name = "Wombo Rollo",
        DisplayName = "Wombo Rollo",
        Rarity = "Epic",
        Price = 42500,
        Generation = 275,
    },
    ["Penguino Cocosino"] = {
        Name = "Penguino Cocosino",
        DisplayName = "Penguino Cocosino",
        Rarity = "Epic",
        Price = 45000,
        Generation = 300,
    },
    ["Mummio Rappitto"] = {
        Name = "Mummio Rappitto",
        DisplayName = "Mummio Rappitto",
        Rarity = "Epic",
        Price = 47500,
        Generation = 325,
    },
    ["Chimpanzini Bananini"] = {
        Name = "Chimpanzini Bananini",
        DisplayName = "Chimpanzini Bananini",
        Rarity = "Legendary",
        Price = 50000,
        Generation = 300,
    },
    ["Tirilikalika Tirilikalako"] = {
        Name = "Tirilikalika Tirilikalako",
        DisplayName = "Tirilikalika Tirilikalako",
        Rarity = "Legendary",
        Price = 75000,
        Generation = 450,
    },
    ["Ballerina Cappuccina"] = {
        Name = "Ballerina Cappuccina",
        DisplayName = "Ballerina Cappuccina",
        Rarity = "Legendary",
        Price = 100000,
        Generation = 500,
    },
    ["Chef Crabracadabra"] = {
        Name = "Chef Crabracadabra",
        DisplayName = "Chef Crabracadabra",
        Rarity = "Legendary",
        Price = 150000,
        Generation = 600,
    },
    ["Lionel Cactuseli"] = {
        Name = "Lionel Cactuseli",
        DisplayName = "Lionel Cactuseli",
        Rarity = "Legendary",
        Price = 175000,
        Generation = 650,
    },
    ["Glorbo Fruttodrillo"] = {
        Name = "Glorbo Fruttodrillo",
        DisplayName = "Glorbo Fruttodrillo",
        Rarity = "Legendary",
        Price = 200000,
        Generation = 750,
    },
    ["Quivioli Ameleonni"] = {
        Name = "Quivioli Ameleonni",
        DisplayName = "Quivioli Ameleonni",
        Rarity = "Legendary",
        Price = 225000,
        Generation = 900,
    },
    ["Blueberrinni Octopusini"] = {
        Name = "Blueberrinni Octopusini",
        DisplayName = "Blueberrinni Octopusini",
        Rarity = "Legendary",
        Price = 250000,
        Generation = 1000,
    },
    ["Clickerino Crabo"] = {
        Name = "Clickerino Crabo",
        DisplayName = "Clickerino Crabo",
        Rarity = "Legendary",
        Price = 250000,
        Generation = 1000,
    },
    ["Caramello Filtrello"] = {
        Name = "Caramello Filtrello",
        DisplayName = "Caramello Filtrello",
        Rarity = "Legendary",
        Price = 255000,
        Generation = 1050,
    },
    ["Pipi Potato"] = {
        Name = "Pipi Potato",
        DisplayName = "Pipi Potato",
        Rarity = "Legendary",
        Price = 265000,
        Generation = 1100,
    },
    ["Strawberrelli Flamingelli"] = {
        Name = "Strawberrelli Flamingelli",
        DisplayName = "Strawberrelli Flamingelli",
        Rarity = "Legendary",
        Price = 275000,
        Generation = 1150,
    },
    ["Cocosini Mama"] = {
        Name = "Cocosini Mama",
        DisplayName = "Cocosini Mama",
        Rarity = "Legendary",
        Price = 285000,
        Generation = 1200,
    },
    ["Pandaccini Bananini"] = {
        Name = "Pandaccini Bananini",
        DisplayName = "Pandaccini Bananini",
        Rarity = "Legendary",
        Price = 300000,
        Generation = 1250,
    },
    ["Quackula"] = {
        Name = "Quackula",
        DisplayName = "Quackula",
        Rarity = "Legendary",
        Price = 310000,
        Generation = 1275,
    },
    ["Pi Pi Watermelon"] = {
        Name = "Pi Pi Watermelon",
        DisplayName = "Pi Pi Watermelon",
        Rarity = "Legendary",
        Price = 315000,
        Generation = 1300,
    },
    ["Signore Carapace"] = {
        Name = "Signore Carapace",
        DisplayName = "Signore Carapace",
        Rarity = "Legendary",
        Price = 320000,
        Generation = 1325,
    },
    ["Sigma Boy"] = {
        Name = "Sigma Boy",
        DisplayName = "Sigma Boy",
        Rarity = "Legendary",
        Price = 325000,
        Generation = 1350,
    },
    ["Sigma Girl"] = {
        Name = "Sigma Girl",
        DisplayName = "Sigma Girl",
        Rarity = "Legendary",
        Price = 340000,
        Generation = 1800,
    },
    ["Buho de Fuego"] = {
        Name = "Buho de Fuego",
        DisplayName = "Buho de Fuego",
        Rarity = "Legendary",
        Price = 345000,
        Generation = 1850,
    },
    ["Frigo Camelo"] = {
        Name = "Frigo Camelo",
        DisplayName = "Frigo Camelo",
        Rarity = "Mythic",
        Price = 350000,
        Generation = 1900,
    },
    ["Orangutini Ananassini"] = {
        Name = "Orangutini Ananassini",
        DisplayName = "Orangutini Ananassini",
        Rarity = "Mythic",
        Price = 400000,
        Generation = 2000,
    },
    ["Rhino Toasterino"] = {
        Name = "Rhino Toasterino",
        DisplayName = "Rhino Toasterino",
        Rarity = "Mythic",
        Price = 450000,
        Generation = 2150,
    },
    ["Bombardiro Crocodilo"] = {
        Name = "Bombardiro Crocodilo",
        DisplayName = "Bombardiro Crocodilo",
        Rarity = "Mythic",
        Price = 500000,
        Generation = 2500,
    },
    ["Brutto Gialutto"] = {
        Name = "Brutto Gialutto",
        DisplayName = "Brutto Gialutto",
        Rarity = "Mythic",
        Price = 600000,
        Generation = 3000,
    },
    ["Spioniro Golubiro"] = {
        Name = "Spioniro Golubiro",
        DisplayName = "Spioniro Golubiro",
        Rarity = "Mythic",
        Price = 750000,
        Generation = 3500,
    },
    ["Bombombini Gusini"] = {
        Name = "Bombombini Gusini",
        DisplayName = "Bombombini Gusini",
        Rarity = "Mythic",
        Price = 1000000,
        Generation = 5000,
    },
    ["Zibra Zubra Zibralini"] = {
        Name = "Zibra Zubra Zibralini",
        DisplayName = "Zibra Zubra Zibralini",
        Rarity = "Mythic",
        Price = 1500000,
        Generation = 6000,
    },
    ["Tigrilini Watermelini"] = {
        Name = "Tigrilini Watermelini",
        DisplayName = "Tigrilini Watermelini",
        Rarity = "Mythic",
        Price = 1750000,
        Generation = 6500,
    },
    ["Avocadorilla"] = {
        Name = "Avocadorilla",
        DisplayName = "Avocadorilla",
        Rarity = "Mythic",
        Price = 2000000,
        Generation = 7000,
    },
    ["Cavallo Virtuoso"] = {
        Name = "Cavallo Virtuoso",
        DisplayName = "Cavallo Virtuoso",
        Rarity = "Mythic",
        Price = 2500000,
        Generation = 7500,
    },
    ["Mythic Lucky Block"] = {
        Name = "Mythic Lucky Block",
        DisplayName = "Lucky Block",
        Rarity = "Mythic",
        Price = 2500000,
        Generation = 0,
    },
    ["Gorillo Subwoofero"] = {
        Name = "Gorillo Subwoofero",
        DisplayName = "Gorillo Subwoofero",
        Rarity = "Mythic",
        Price = 2750000,
        Generation = 7750,
    },
    ["Stoppo Luminino"] = {
        Name = "Stoppo Luminino",
        DisplayName = "Stoppo Luminino",
        Rarity = "Mythic",
        Price = 3000000,
        Generation = 8000,
    },
    ["Gorillo Watermelondrillo"] = {
        Name = "Gorillo Watermelondrillo",
        DisplayName = "Gorillo Watermelondrillo",
        Rarity = "Mythic",
        Price = 3000000,
        Generation = 8000,
    },
    ["Tob Tobi Tobi"] = {
        Name = "Tob Tobi Tobi",
        DisplayName = "Tob Tobi Tobi",
        Rarity = "Mythic",
        Price = 3250000,
        Generation = 8500,
    },
    ["Lerulerulerule"] = {
        Name = "Lerulerulerule",
        DisplayName = "Lerulerulerule",
        Rarity = "Mythic",
        Price = 3500000,
        Generation = 8750,
    },
    ["Ganganzelli Trulala"] = {
        Name = "Ganganzelli Trulala",
        DisplayName = "Ganganzelli Trulala",
        Rarity = "Mythic",
        Price = 3750000,
        Generation = 9000,
    },
    ["Te Te Te Sahur"] = {
        Name = "Te Te Te Sahur",
        DisplayName = "Te Te Te Sahur",
        Rarity = "Mythic",
        Price = 4000000,
        Generation = 9500,
    },
    ["Rhino Helicopterino"] = {
        Name = "Rhino Helicopterino",
        DisplayName = "Rhino Helicopterino",
        Rarity = "Mythic",
        Price = 4100000,
        Generation = 11000,
    },
    ["Magi Ribbitini"] = {
        Name = "Magi Ribbitini",
        DisplayName = "Magi Ribbitini",
        Rarity = "Mythic",
        Price = 4200000,
        Generation = 11500,
    },
    ["Tracoducotulu Delapeladustuz"] = {
        Name = "Tracoducotulu Delapeladustuz",
        DisplayName = "Tracoducotulu Delapeladustuz",
        Rarity = "Mythic",
        Price = 4250000,
        Generation = 12000,
    },
    ["Los Noobinis"] = {
        Name = "Los Noobinis",
        DisplayName = "Los Noobinis",
        Rarity = "Mythic",
        Price = 4350000,
        Generation = 12500,
    },
    ["Cachorrito Melonito"] = {
        Name = "Cachorrito Melonito",
        DisplayName = "Cachorrito Melonito",
        Rarity = "Mythic",
        Price = 4400000,
        Generation = 13000,
    },
    ["Carloo"] = {
        Name = "Carloo",
        DisplayName = "Carloo",
        Rarity = "Mythic",
        Price = 4500000,
        Generation = 13500,
    },
    ["Elefanto Frigo"] = {
        Name = "Elefanto Frigo",
        DisplayName = "Elefanto Frigo",
        Rarity = "Mythic",
        Price = 4600000,
        Generation = 14000,
    },
    ["Carrotini Brainini"] = {
        Name = "Carrotini Brainini",
        DisplayName = "Carrotini Brainini",
        Rarity = "Mythic",
        Price = 4750000,
        Generation = 15000,
    },
    ["Centrucci Nuclucci"] = {
        Name = "Centrucci Nuclucci",
        DisplayName = "Centrucci Nuclucci",
        Rarity = "Mythic",
        Price = 4800000,
        Generation = 15500,
    },
    ["Toiletto Focaccino"] = {
        Name = "Toiletto Focaccino",
        DisplayName = "Toiletto Focaccino",
        Rarity = "Mythic",
        Price = 4850000,
        Generation = 16000,
    },
    ["Jacko Spaventosa"] = {
        Name = "Jacko Spaventosa",
        DisplayName = "Jacko Spaventosa",
        Rarity = "Mythic",
        Price = 4875000,
        Generation = 16250,
    },
    ["Bananito Bandito"] = {
        Name = "Bananito Bandito",
        DisplayName = "Bananito Bandito",
        Rarity = "Mythic",
        Price = 4900000,
        Generation = 16500,
    },
    ["Cocofanto Elefanto"] = {
        Name = "Cocofanto Elefanto",
        DisplayName = "Cocofanto Elefanto",
        Rarity = "Brainrot God",
        Price = 5000000,
        Generation = 17500,
    },
    ["Antonio"] = {
        Name = "Antonio",
        DisplayName = "Antonio",
        Rarity = "Brainrot God",
        Price = 6000000,
        Generation = 18500,
    },
    ["Gattatino Nyanino"] = {
        Name = "Gattatino Nyanino",
        DisplayName = "Gattatino Nyanino",
        Rarity = "Brainrot God",
        Price = 7500000,
        Generation = 35000,
    },
    ["Girafa Celestre"] = {
        Name = "Girafa Celestre",
        DisplayName = "Girafa Celestre",
        Rarity = "Brainrot God",
        Price = 7500000,
        Generation = 20000,
    },
    ["Chihuanini Taconini"] = {
        Name = "Chihuanini Taconini",
        DisplayName = "Chihuanini Taconini",
        Rarity = "Brainrot God",
        Price = 8500000,
        Generation = 45000,
    },
    ["Matteo"] = {
        Name = "Matteo",
        DisplayName = "Matteo",
        Rarity = "Brainrot God",
        Price = 10000000,
        Generation = 50000,
    },
    ["Tralalero Tralala"] = {
        Name = "Tralalero Tralala",
        DisplayName = "Tralalero Tralala",
        Rarity = "Brainrot God",
        Price = 10000000,
        Generation = 50000,
    },
    ["Los Crocodillitos"] = {
        Name = "Los Crocodillitos",
        DisplayName = "Los Crocodillitos",
        Rarity = "Brainrot God",
        Price = 12500000,
        Generation = 55000,
    },
    ["Tigroligre Frutonni"] = {
        Name = "Tigroligre Frutonni",
        DisplayName = "Tigroligre Frutonni",
        Rarity = "Brainrot God",
        Price = 14000000,
        Generation = 60000,
    },
    ["Odin Din Din Dun"] = {
        Name = "Odin Din Din Dun",
        DisplayName = "Odin Din Din Dun",
        Rarity = "Brainrot God",
        Price = 15000000,
        Generation = 75000,
    },
    ["Money Money Man"] = {
        Name = "Money Money Man",
        DisplayName = "Money Money Man",
        Rarity = "Brainrot God",
        Price = 17500000,
        Generation = 65000,
    },
    ["Alessio"] = {
        Name = "Alessio",
        DisplayName = "Alessio",
        Rarity = "Brainrot God",
        Price = 17500000,
        Generation = 85000,
    },
    ["Tralalita Tralala"] = {
        Name = "Tralalita Tralala",
        DisplayName = "Tralalita Tralala",
        Rarity = "Brainrot God",
        Price = 20000000,
        Generation = 100000,
    },
    ["Unclito Samito"] = {
        Name = "Unclito Samito",
        DisplayName = "Unclito Samito",
        Rarity = "Brainrot God",
        Price = 20000000,
        Generation = 75000,
    },
    ["Tipi Topi Taco"] = {
        Name = "Tipi Topi Taco",
        DisplayName = "Tipi Topi Taco",
        Rarity = "Brainrot God",
        Price = 20000000,
        Generation = 75000,
    },
    ["Tukanno Bananno"] = {
        Name = "Tukanno Bananno",
        DisplayName = "Tukanno Bananno",
        Rarity = "Brainrot God",
        Price = 22500000,
        Generation = 100000,
    },
    ["Extinct Ballerina"] = {
        Name = "Extinct Ballerina",
        DisplayName = "Extinct Ballerina",
        Rarity = "Brainrot God",
        Price = 23500000,
        Generation = 125000,
    },
    ["Vampira Cappucina"] = {
        Name = "Vampira Cappucina",
        DisplayName = "Vampira Cappucina",
        Rarity = "Brainrot God",
        Price = 24500000,
        Generation = 125000,
    },
    ["Espresso Signora"] = {
        Name = "Espresso Signora",
        DisplayName = "Espresso Signora",
        Rarity = "Brainrot God",
        Price = 25000000,
        Generation = 70000,
    },
    ["Orcalero Orcala"] = {
        Name = "Orcalero Orcala",
        DisplayName = "Orcalero Orcala",
        Rarity = "Brainrot God",
        Price = 25000000,
        Generation = 100000,
    },
    ["Trenostruzzo Turbo 3000"] = {
        Name = "Trenostruzzo Turbo 3000",
        DisplayName = "Trenostruzzo Turbo 3000",
        Rarity = "Brainrot God",
        Price = 25000000,
        Generation = 150000,
    },
    ["Brainrot God Lucky Block"] = {
        Name = "Brainrot God Lucky Block",
        DisplayName = "Lucky Block",
        Rarity = "Brainrot God",
        Price = 25000000,
        Generation = 0,
    },
    ["Urubini Flamenguini"] = {
        Name = "Urubini Flamenguini",
        DisplayName = "Urubini Flamenguini",
        Rarity = "Brainrot God",
        Price = 30000000,
        Generation = 150000,
    },
    ["Trippi Troppi Troppa Trippa"] = {
        Name = "Trippi Troppi Troppa Trippa",
        DisplayName = "Trippi Troppi Troppa Trippa",
        Rarity = "Brainrot God",
        Price = 30000000,
        Generation = 175000,
    },
    ["Jacko Jack Jack"] = {
        Name = "Jacko Jack Jack",
        DisplayName = "Jacko Jack Jack",
        Rarity = "Brainrot God",
        Price = 30000000,
        Generation = 150000,
    },
    ["Capi Taco"] = {
        Name = "Capi Taco",
        DisplayName = "Capi Taco",
        Rarity = "Brainrot God",
        Price = 31000000,
        Generation = 155000,
    },
    ["Las Capuchinas"] = {
        Name = "Las Capuchinas",
        DisplayName = "Las Capuchinas",
        Rarity = "Brainrot God",
        Price = 32500000,
        Generation = 185000,
    },
    ["Gattito Tacoto"] = {
        Name = "Gattito Tacoto",
        DisplayName = "Gattito Tacoto",
        Rarity = "Brainrot God",
        Price = 32500000,
        Generation = 165000,
    },
    ["Bulbito Bandito Traktorito"] = {
        Name = "Bulbito Bandito Traktorito",
        DisplayName = "Bulbito Bandito Traktorito",
        Rarity = "Brainrot God",
        Price = 35000000,
        Generation = 205000,
    },
    ["Ballerino Lololo"] = {
        Name = "Ballerino Lololo",
        DisplayName = "Ballerino Lololo",
        Rarity = "Brainrot God",
        Price = 35000000,
        Generation = 200000,
    },
    ["Pakrahmatmamat"] = {
        Name = "Pakrahmatmamat",
        DisplayName = "Pakrahmatmamat",
        Rarity = "Brainrot God",
        Price = 37500000,
        Generation = 215000,
    },
    ["Los Tungtungtungcitos"] = {
        Name = "Los Tungtungtungcitos",
        DisplayName = "Los Tungtungtungcitos",
        Rarity = "Brainrot God",
        Price = 37500000,
        Generation = 210000,
    },
    ["Brr es Teh Patipum"] = {
        Name = "Brr es Teh Patipum",
        DisplayName = "Brr es Teh Patipum",
        Rarity = "Brainrot God",
        Price = 40000000,
        Generation = 225000,
    },
    ["Piccione Macchina"] = {
        Name = "Piccione Macchina",
        DisplayName = "Piccione Macchina",
        Rarity = "Brainrot God",
        Price = 40000000,
        Generation = 225000,
    },
    ["Pakrahmatmatina"] = {
        Name = "Pakrahmatmatina",
        DisplayName = "Pakrahmatmatina",
        Rarity = "Brainrot God",
        Price = 40500000,
        Generation = 225000,
    },
    ["Tractoro Dinosauro"] = {
        Name = "Tractoro Dinosauro",
        DisplayName = "Tractoro Dinosauro",
        Rarity = "Brainrot God",
        Price = 42500000,
        Generation = 230000,
    },
    ["Los Bombinitos"] = {
        Name = "Los Bombinitos",
        DisplayName = "Los Bombinitos",
        Rarity = "Brainrot God",
        Price = 42500000,
        Generation = 220000,
    },
    ["Tartaruga Cisterna"] = {
        Name = "Tartaruga Cisterna",
        DisplayName = "Tartaruga Cisterna",
        Rarity = "Brainrot God",
        Price = 45000000,
        Generation = 250000,
    },
    ["Los Orcalitos"] = {
        Name = "Los Orcalitos",
        DisplayName = "Los Orcalitos",
        Rarity = "Brainrot God",
        Price = 45000000,
        Generation = 235000,
    },
    ["Snailenzo"] = {
        Name = "Snailenzo",
        DisplayName = "Snailenzo",
        Rarity = "Brainrot God",
        Price = 45000000,
        Generation = 250000,
    },
    ["Mummy Ambalabu"] = {
        Name = "Mummy Ambalabu",
        DisplayName = "Mummy Ambalabu",
        Rarity = "Brainrot God",
        Price = 45000000,
        Generation = 250000,
    },
    ["Corn Corn Corn Sahur"] = {
        Name = "Corn Corn Corn Sahur",
        DisplayName = "Corn Corn Corn Sahur",
        Rarity = "Brainrot God",
        Price = 45000000,
        Generation = 250000,
    },
    ["Orcalita Orcala"] = {
        Name = "Orcalita Orcala",
        DisplayName = "Orcalita Orcala",
        Rarity = "Brainrot God",
        Price = 45000000,
        Generation = 240000,
    },
    ["Squalanana"] = {
        Name = "Squalanana",
        DisplayName = "Squalanana",
        Rarity = "Brainrot God",
        Price = 45000000,
        Generation = 250000,
    },
    ["Cacasito Satalito"] = {
        Name = "Cacasito Satalito",
        DisplayName = "Cacasito Satalito",
        Rarity = "Brainrot God",
        Price = 45000000,
        Generation = 240000,
    },
    ["Dug dug dug"] = {
        Name = "Dug dug dug",
        DisplayName = "Dug dug dug",
        Rarity = "Brainrot God",
        Price = 45500000,
        Generation = 255000,
    },
    ["Aquanaut"] = {
        Name = "Aquanaut",
        DisplayName = "Aquanaut",
        Rarity = "Brainrot God",
        Price = 45500000,
        Generation = 245000,
    },
    ["Crabbo Limonetta"] = {
        Name = "Crabbo Limonetta",
        DisplayName = "Crabbo Limonetta",
        Rarity = "Brainrot God",
        Price = 46000000,
        Generation = 235000,
    },
    ["Los Tipi Tacos"] = {
        Name = "Los Tipi Tacos",
        DisplayName = "Los Tipi Tacos",
        Rarity = "Brainrot God",
        Price = 46000000,
        Generation = 260000,
    },
    ["Frio Ninja"] = {
        Name = "Frio Ninja",
        DisplayName = "Frio Ninja",
        Rarity = "Brainrot God",
        Price = 46500000,
        Generation = 265000,
    },
    ["Piccionetta Macchina"] = {
        Name = "Piccionetta Macchina",
        DisplayName = "Piccionetta Macchina",
        Rarity = "Brainrot God",
        Price = 47000000,
        Generation = 270000,
    },
    ["Bambu Bambu Sahur"] = {
        Name = "Bambu Bambu Sahur",
        DisplayName = "Bambu Bambu Sahur",
        Rarity = "Brainrot God",
        Price = 47500000,
        Generation = 275000,
    },
    ["Mastodontico Telepiedone"] = {
        Name = "Mastodontico Telepiedone",
        DisplayName = "Mastodontico Telepiedone",
        Rarity = "Brainrot God",
        Price = 47500000,
        Generation = 275000,
    },
    ["Anpali Babel"] = {
        Name = "Anpali Babel",
        DisplayName = "Anpali Babel",
        Rarity = "Brainrot God",
        Price = 48000000,
        Generation = 280000,
    },
    ["Cappuccino Clownino"] = {
        Name = "Cappuccino Clownino",
        DisplayName = "Cappuccino Clownino",
        Rarity = "Brainrot God",
        Price = 48500000,
        Generation = 285000,
    },
    ["Bombardini Tortinii"] = {
        Name = "Bombardini Tortinii",
        DisplayName = "Bombardini Tortinii",
        Rarity = "Brainrot God",
        Price = 50000000,
        Generation = 225000,
    },
    ["La Vacca Saturno Saturnita"] = {
        Name = "La Vacca Saturno Saturnita",
        DisplayName = "La Vacca Saturno Saturnita",
        Rarity = "Secret",
        Price = 50000000,
        Generation = 300000,
    },
    ["Taco Lucky Block"] = {
        Name = "Taco Lucky Block",
        DisplayName = "Lucky Block",
        Rarity = "Taco",
        Price = 50000000,
        Generation = 0,
    },
    ["Brasilini Berimbini"] = {
        Name = "Brasilini Berimbini",
        DisplayName = "Brasilini Berimbini",
        Rarity = "Brainrot God",
        Price = 55000000,
        Generation = 285000,
    },
    ["Krupuk Pagi Pagi"] = {
        Name = "Krupuk Pagi Pagi",
        DisplayName = "Krupuk Pagi Pagi",
        Rarity = "Brainrot God",
        Price = 60000000,
        Generation = 290000,
    },
    ["Belula Beluga"] = {
        Name = "Belula Beluga",
        DisplayName = "Belula Beluga",
        Rarity = "Brainrot God",
        Price = 60000000,
        Generation = 290000,
    },
    ["Skull Skull Skull"] = {
        Name = "Skull Skull Skull",
        DisplayName = "Skull Skull Skull",
        Rarity = "Brainrot God",
        Price = 60000000,
        Generation = 290000,
    },
    ["Tentacolo Tecnico"] = {
        Name = "Tentacolo Tecnico",
        DisplayName = "Tentacolo Tecnico",
        Rarity = "Brainrot God",
        Price = 62500000,
        Generation = 292500,
    },
    ["Pop Pop Sahur"] = {
        Name = "Pop Pop Sahur",
        DisplayName = "Pop Pop Sahur",
        Rarity = "Brainrot God",
        Price = 65000000,
        Generation = 295000,
    },
    ["Noo La Polizia"] = {
        Name = "Noo La Polizia",
        DisplayName = "Noo La Polizia",
        Rarity = "Brainrot God",
        Price = 67000000,
        Generation = 280000,
    },
    ["Sammyni Spyderini"] = {
        Name = "Sammyni Spyderini",
        DisplayName = "Sammyni Spyderini",
        Rarity = "Secret",
        Price = 75000000,
        Generation = 325000,
    },
    ["Blackhole Goat"] = {
        Name = "Blackhole Goat",
        DisplayName = "Blackhole Goat",
        Rarity = "Secret",
        Price = 75000000,
        Generation = 400000,
    },
    ["Bisonte Giuppitere"] = {
        Name = "Bisonte Giuppitere",
        DisplayName = "Bisonte Giuppitere",
        Rarity = "Secret",
        Price = 75000000,
        Generation = 300000,
    },
    ["Agarrini la Palini"] = {
        Name = "Agarrini la Palini",
        DisplayName = "Agarrini la Palini",
        Rarity = "Secret",
        Price = 80000000,
        Generation = 425000,
    },
    ["Jackorilla"] = {
        Name = "Jackorilla",
        DisplayName = "Jackorilla",
        Rarity = "Secret",
        Price = 80000000,
        Generation = 315000,
    },
    ["Chachechi"] = {
        Name = "Chachechi",
        DisplayName = "Chachechi",
        Rarity = "Secret",
        Price = 85000000,
        Generation = 400000,
    },
    ["Los Tortus"] = {
        Name = "Los Tortus",
        DisplayName = "Los Tortus",
        Rarity = "Secret",
        Price = 100000000,
        Generation = 500000,
    },
    ["Karkerkar Kurkur"] = {
        Name = "Karkerkar Kurkur",
        DisplayName = "Karkerkar Kurkur",
        Rarity = "Secret",
        Price = 100000000,
        Generation = 300000,
    },
    ["Admin Lucky Block"] = {
        Name = "Admin Lucky Block",
        DisplayName = "Lucky Block",
        Rarity = "Admin",
        Price = 100000000,
        Generation = 0,
    },
    ["Los Matteos"] = {
        Name = "Los Matteos",
        DisplayName = "Los Matteos",
        Rarity = "Secret",
        Price = 100000000,
        Generation = 300000,
    },
    ["Los Tralaleritos"] = {
        Name = "Los Tralaleritos",
        DisplayName = "Los Tralaleritos",
        Rarity = "Secret",
        Price = 100000000,
        Generation = 500000,
    },
    ["Zombie Tralala"] = {
        Name = "Zombie Tralala",
        DisplayName = "Zombie Tralala",
        Rarity = "Secret",
        Price = 100000000,
        Generation = 500000,
    },
    ["Trenostruzzo Turbo 4000"] = {
        Name = "Trenostruzzo Turbo 4000",
        DisplayName = "Trenostruzzo Turbo 4000",
        Rarity = "Secret",
        Price = 100000000,
        Generation = 310000,
    },
    ["La Cucaracha"] = {
        Name = "La Cucaracha",
        DisplayName = "La Cucaracha",
        Rarity = "Secret",
        Price = 110000000,
        Generation = 475000,
    },
    ["Vulturino Skeletono"] = {
        Name = "Vulturino Skeletono",
        DisplayName = "Vulturino Skeletono",
        Rarity = "Secret",
        Price = 110000000,
        Generation = 500000,
    },
    ["Boatito Auratito"] = {
        Name = "Boatito Auratito",
        DisplayName = "Boatito Auratito",
        Rarity = "Secret",
        Price = 115000000,
        Generation = 525000,
    },
    ["Guerriro Digitale"] = {
        Name = "Guerriro Digitale",
        DisplayName = "Guerriro Digitale",
        Rarity = "Secret",
        Price = 120000000,
        Generation = 550000,
    },
    ["Torrtuginni Dragonfrutini"] = {
        Name = "Torrtuginni Dragonfrutini",
        DisplayName = "Torrtuginni Dragonfrutini",
        Rarity = "Secret",
        Price = 125000000,
        Generation = 350000,
    },
    ["Los Spyderinis"] = {
        Name = "Los Spyderinis",
        DisplayName = "Los Spyderinis",
        Rarity = "Secret",
        Price = 125000000,
        Generation = 425000,
    },
    ["Fragola La La La"] = {
        Name = "Fragola La La La",
        DisplayName = "Fragola La La La",
        Rarity = "Secret",
        Price = 125000000,
        Generation = 450000,
    },
    ["Extinct Tralalero"] = {
        Name = "Extinct Tralalero",
        DisplayName = "Extinct Tralalero",
        Rarity = "Secret",
        Price = 125000000,
        Generation = 450000,
    },
    ["Yess my examine"] = {
        Name = "Yess my examine",
        DisplayName = "Yess my examine",
        Rarity = "Secret",
        Price = 130000000,
        Generation = 575000,
    },
    ["Extinct Matteo"] = {
        Name = "Extinct Matteo",
        DisplayName = "Extinct Matteo",
        Rarity = "Secret",
        Price = 140000000,
        Generation = 625000,
    },
    ["Las Tralaleritas"] = {
        Name = "Las Tralaleritas",
        DisplayName = "Las Tralaleritas",
        Rarity = "Secret",
        Price = 150000000,
        Generation = 650000,
    },
    ["Dul Dul Dul"] = {
        Name = "Dul Dul Dul",
        DisplayName = "Dul Dul Dul",
        Rarity = "Secret",
        Price = 150000000,
        Generation = 375000,
    },
    ["La Karkerkar Combinasion"] = {
        Name = "La Karkerkar Combinasion",
        DisplayName = "La Karkerkar Combinasion",
        Rarity = "Secret",
        Price = 160000000,
        Generation = 600000,
    },
    ["Pumpkini Spyderini"] = {
        Name = "Pumpkini Spyderini",
        DisplayName = "Pumpkini Spyderini",
        Rarity = "Secret",
        Price = 165000000,
        Generation = 650000,
    },
    ["Frankentteo"] = {
        Name = "Frankentteo",
        DisplayName = "Frankentteo",
        Rarity = "Secret",
        Price = 175000000,
        Generation = 700000,
    },
    ["Job Job Job Sahur"] = {
        Name = "Job Job Job Sahur",
        DisplayName = "Job Job Job Sahur",
        Rarity = "Secret",
        Price = 175000000,
        Generation = 700000,
    },
    ["Karker Sahur"] = {
        Name = "Karker Sahur",
        DisplayName = "Karker Sahur",
        Rarity = "Secret",
        Price = 185000000,
        Generation = 725000,
    },
    ["Las Vaquitas Saturnitas"] = {
        Name = "Las Vaquitas Saturnitas",
        DisplayName = "Las Vaquitas Saturnitas",
        Rarity = "Secret",
        Price = 200000000,
        Generation = 750000,
    },
    ["Los Karkeritos"] = {
        Name = "Los Karkeritos",
        DisplayName = "Los Karkeritos",
        Rarity = "Secret",
        Price = 200000000,
        Generation = 750000,
    },
    ["La Vacca Jacko Linterino"] = {
        Name = "La Vacca Jacko Linterino",
        DisplayName = "La Vacca Jacko Linterino",
        Rarity = "Secret",
        Price = 225000000,
        Generation = 850000,
    },
    ["Trickolino"] = {
        Name = "Trickolino",
        DisplayName = "Trickolino",
        Rarity = "Secret",
        Price = 235000000,
        Generation = 900000,
    },
    ["Los Lucky Blocks"] = {
        Name = "Los Lucky Blocks",
        DisplayName = "Los Lucky Blocks",
        Rarity = "Admin",
        Price = 250000000,
        Generation = 0,
    },
    ["Graipuss Medussi"] = {
        Name = "Graipuss Medussi",
        DisplayName = "Graipuss Medussi",
        Rarity = "Secret",
        Price = 250000000,
        Generation = 1000000,
    },
    ["Perrito Burrito"] = {
        Name = "Perrito Burrito",
        DisplayName = "Perrito Burrito",
        Rarity = "Secret",
        Price = 250000000,
        Generation = 1000000,
    },
    ["1x1x1x1"] = {
        Name = "1x1x1x1",
        DisplayName = "1x1x1x1",
        Rarity = "Secret",
        Price = 255555555,
        Generation = 1111111,
    },
    ["Spooky Lucky Block"] = {
        Name = "Spooky Lucky Block",
        DisplayName = "Spooky Lucky Block",
        Rarity = "Spooky",
        Price = 350000000,
        Generation = 0,
    },
    ["Los Jobcitos"] = {
        Name = "Los Jobcitos",
        DisplayName = "Los Jobcitos",
        Rarity = "Secret",
        Price = 500000000,
        Generation = 1500000,
    },
    ["Nooo My Hotspot"] = {
        Name = "Nooo My Hotspot",
        DisplayName = "Nooo My Hotspot",
        Rarity = "Secret",
        Price = 500000000,
        Generation = 1500000,
    },
    ["Noo my examine"] = {
        Name = "Noo my examine",
        DisplayName = "Noo my examine",
        Rarity = "Secret",
        Price = 525000000,
        Generation = 1750000,
    },
    ["La Sahur Combinasion"] = {
        Name = "La Sahur Combinasion",
        DisplayName = "La Sahur Combinasion",
        Rarity = "Secret",
        Price = 550000000,
        Generation = 2000000,
    },
    ["Telemorte"] = {
        Name = "Telemorte",
        DisplayName = "Telemorte",
        Rarity = "Secret",
        Price = 550000000,
        Generation = 2000000,
    },
    ["To to to Sahur"] = {
        Name = "To to to Sahur",
        DisplayName = "To to to Sahur",
        Rarity = "Secret",
        Price = 575000000,
        Generation = 2250000,
    },
    ["Pirulitoita Bicicleteira"] = {
        Name = "Pirulitoita Bicicleteira",
        DisplayName = "Pirulitoita Bicicleteira",
        Rarity = "Secret",
        Price = 600000000,
        Generation = 2500000,
    },
    ["Pot Hotspot"] = {
        Name = "Pot Hotspot",
        DisplayName = "Pot Hotspot",
        Rarity = "Secret",
        Price = 600000000,
        Generation = 2500000,
    },
    ["Horegini Boom"] = {
        Name = "Horegini Boom",
        DisplayName = "Horegini Boom",
        Rarity = "Secret",
        Price = 650000000,
        Generation = 2750000,
    },
    ["Pot Pumpkin"] = {
        Name = "Pot Pumpkin",
        DisplayName = "Pot Pumpkin",
        Rarity = "Secret",
        Price = 700000000,
        Generation = 3000000,
    },
    ["Quesadilla Crocodila"] = {
        Name = "Quesadilla Crocodila",
        DisplayName = "Quesadilla Crocodila",
        Rarity = "Secret",
        Price = 700000000,
        Generation = 3000000,
    },
    ["Quesadillo Vampiro"] = {
        Name = "Quesadillo Vampiro",
        DisplayName = "Quesadillo Vampiro",
        Rarity = "Secret",
        Price = 750000000,
        Generation = 3500000,
    },
    ["Secret Lucky Block"] = {
        Name = "Secret Lucky Block",
        DisplayName = "Lucky Block",
        Rarity = "Secret",
        Price = 750000000,
        Generation = 0,
    },
    ["Chicleteira Bicicleteira"] = {
        Name = "Chicleteira Bicicleteira",
        DisplayName = "Chicleteira Bicicleteira",
        Rarity = "Secret",
        Price = 750000000,
        Generation = 3500000,
    },
    ["Burrito Bandito"] = {
        Name = "Burrito Bandito",
        DisplayName = "Burrito Bandito",
        Rarity = "Secret",
        Price = 850000000,
        Generation = 4000000,
    },
    ["Chicleteirina Bicicleteirina"] = {
        Name = "Chicleteirina Bicicleteirina",
        DisplayName = "Chicleteirina Bicicleteirina",
        Rarity = "Secret",
        Price = 850000000,
        Generation = 4000000,
    },
    ["Noo my Candy"] = {
        Name = "Noo my Candy",
        DisplayName = "Noo my Candy",
        Rarity = "Secret",
        Price = 900000000,
        Generation = 5000000,
    },
    ["La Grande Combinasion"] = {
        Name = "La Grande Combinasion",
        DisplayName = "La Grande Combinasion",
        Rarity = "Secret",
        Price = 1000000000,
        Generation = 10000000,
    },
    ["Los Nooo My Hotspotsitos"] = {
        Name = "Los Nooo My Hotspotsitos",
        DisplayName = "Los Nooo My Hotspotsitos",
        Rarity = "Secret",
        Price = 1000000000,
        Generation = 5500000,
    },
    ["Rang Ring Bus"] = {
        Name = "Rang Ring Bus",
        DisplayName = "Rang Ring Bus",
        Rarity = "Secret",
        Price = 1100000000,
        Generation = 6000000,
    },
    ["Guest 666"] = {
        Name = "Guest 666",
        DisplayName = "Guest 666",
        Rarity = "Secret",
        Price = 1166666666,
        Generation = 6666666,
    },
    ["Los Chicleteiras"] = {
        Name = "Los Chicleteiras",
        DisplayName = "Los Chicleteiras",
        Rarity = "Secret",
        Price = 1200000000,
        Generation = 7000000,
    },
    ["67"] = {
        Name = "67",
        DisplayName = "67",
        Rarity = "Secret",
        Price = 1250000000,
        Generation = 7500000,
    },
    ["Mariachi Corazoni"] = {
        Name = "Mariachi Corazoni",
        DisplayName = "Mariachi Corazoni",
        Rarity = "Secret",
        Price = 1750000000,
        Generation = 12500000,
    },
    ["Swag Soda"] = {
        Name = "Swag Soda",
        DisplayName = "Swag Soda",
        Rarity = "Secret",
        Price = 1800000000,
        Generation = 13000000,
    },
    ["Los Combinasionas"] = {
        Name = "Los Combinasionas",
        DisplayName = "Los Combinasionas",
        Rarity = "Secret",
        Price = 2000000000,
        Generation = 15000000,
    },
    ["Tacorita Bicicleta"] = {
        Name = "Tacorita Bicicleta",
        DisplayName = "Tacorita Bicicleta",
        Rarity = "Secret",
        Price = 2250000000,
        Generation = 16500000,
    },
    ["Las Sis"] = {
        Name = "Las Sis",
        DisplayName = "Las Sis",
        Rarity = "Secret",
        Price = 2500000000,
        Generation = 17500000,
    },
    ["Chillin Chili"] = {
        Name = "Chillin Chili",
        DisplayName = "Chillin Chili",
        Rarity = "Secret",
        Price = 2500000000,
        Generation = 25000000,
    },
    ["Nuclearo Dinossauro"] = {
        Name = "Nuclearo Dinossauro",
        DisplayName = "Nuclearo Dinossauro",
        Rarity = "Secret",
        Price = 2500000000,
        Generation = 15000000,
    },
    ["Chipso and Queso"] = {
        Name = "Chipso and Queso",
        DisplayName = "Chipso and Queso",
        Rarity = "Secret",
        Price = 2500000000,
        Generation = 25000000,
    },
    ["Los Bros"] = {
        Name = "Los Bros",
        DisplayName = "Los Bros",
        Rarity = "Secret",
        Price = 2600000000,
        Generation = 24000000,
    },
    ["Money Money Puggy"] = {
        Name = "Money Money Puggy",
        DisplayName = "Money Money Puggy",
        Rarity = "Secret",
        Price = 2600000000,
        Generation = 21000000,
    },
    ["Los Mobilis"] = {
        Name = "Los Mobilis",
        DisplayName = "Los Mobilis",
        Rarity = "Secret",
        Price = 2700000000,
        Generation = 22000000,
    },
    ["Mieteteira Bicicleteira"] = {
        Name = "Mieteteira Bicicleteira",
        DisplayName = "Mieteteira Bicicleteira",
        Rarity = "Secret",
        Price = 2750000000,
        Generation = 26000000,
    },
    ["Los 67"] = {
        Name = "Los 67",
        DisplayName = "Los 67",
        Rarity = "Secret",
        Price = 2750000000,
        Generation = 22500000,
    },
    ["Celularcini Viciosini"] = {
        Name = "Celularcini Viciosini",
        DisplayName = "Celularcini Viciosini",
        Rarity = "Secret",
        Price = 2750000000,
        Generation = 22500000,
    },
    ["La Spooky Grande"] = {
        Name = "La Spooky Grande",
        DisplayName = "La Spooky Grande",
        Rarity = "Secret",
        Price = 2900000000,
        Generation = 24500000,
    },
    ["Tralaledon"] = {
        Name = "Tralaledon",
        DisplayName = "Tralaledon",
        Rarity = "Secret",
        Price = 3000000000,
        Generation = 27500000,
    },
    ["Los Hotspotsitos"] = {
        Name = "Los Hotspotsitos",
        DisplayName = "Los Hotspotsitos",
        Rarity = "Secret",
        Price = 3000000000,
        Generation = 20000000,
    },
    ["Los Spooky Combinasionas"] = {
        Name = "Los Spooky Combinasionas",
        DisplayName = "Los Spooky Combinasionas",
        Rarity = "Secret",
        Price = 3000000000,
        Generation = 20000000,
    },
    ["Los Puggies"] = {
        Name = "Los Puggies",
        DisplayName = "Los Puggies",
        Rarity = "Secret",
        Price = 3000000000,
        Generation = 30000000,
    },
    ["La Extinct Grande"] = {
        Name = "La Extinct Grande",
        DisplayName = "La Extinct Grande",
        Rarity = "Secret",
        Price = 3250000000,
        Generation = 23500000,
    },
    ["Esok Sekolah"] = {
        Name = "Esok Sekolah",
        DisplayName = "Esok Sekolah",
        Rarity = "Secret",
        Price = 3500000000,
        Generation = 30000000,
    },
    ["Los Primos"] = {
        Name = "Los Primos",
        DisplayName = "Los Primos",
        Rarity = "Secret",
        Price = 3750000000,
        Generation = 31000000,
    },
    ["Eviledon"] = {
        Name = "Eviledon",
        DisplayName = "Eviledon",
        Rarity = "Secret",
        Price = 3850000000,
        Generation = 31500000,
    },
    ["Los Tacoritas"] = {
        Name = "Los Tacoritas",
        DisplayName = "Los Tacoritas",
        Rarity = "Secret",
        Price = 4000000000,
        Generation = 32000000,
    },
    ["Tang Tang Keletang"] = {
        Name = "Tang Tang Keletang",
        DisplayName = "Tang Tang Keletang",
        Rarity = "Secret",
        Price = 4500000000,
        Generation = 33500000,
    },
    ["La Taco Combinasion"] = {
        Name = "La Taco Combinasion",
        DisplayName = "La Taco Combinasion",
        Rarity = "Secret",
        Price = 5000000000,
        Generation = 35000000,
    },
    ["Ketupat Kepat"] = {
        Name = "Ketupat Kepat",
        DisplayName = "Ketupat Kepat",
        Rarity = "Secret",
        Price = 5000000000,
        Generation = 35000000,
    },
    ["Tictac Sahur"] = {
        Name = "Tictac Sahur",
        DisplayName = "Tictac Sahur",
        Rarity = "Secret",
        Price = 6000000000,
        Generation = 37500000,
    },
    ["Orcaledon"] = {
        Name = "Orcaledon",
        DisplayName = "Orcaledon",
        Rarity = "Secret",
        Price = 7000000000,
        Generation = 40000000,
    },
    ["La Supreme Combinasion"] = {
        Name = "La Supreme Combinasion",
        DisplayName = "La Supreme Combinasion",
        Rarity = "Secret",
        Price = 7000000000,
        Generation = 40000000,
    },
    ["Ketchuru and Musturu"] = {
        Name = "Ketchuru and Musturu",
        DisplayName = "Ketchuru and Musturu",
        Rarity = "Secret",
        Price = 7500000000,
        Generation = 42500000,
    },
    ["Garama and Madundung"] = {
        Name = "Garama and Madundung",
        DisplayName = "Garama and Madundung",
        Rarity = "Secret",
        Price = 10000000000,
        Generation = 50000000,
    },
    ["Spaghetti Tualetti"] = {
        Name = "Spaghetti Tualetti",
        DisplayName = "Spaghetti Tualetti",
        Rarity = "Secret",
        Price = 15000000000,
        Generation = 60000000,
    },
    ["Los Spaghettis"] = {
        Name = "Los Spaghettis",
        DisplayName = "Los Spaghettis",
        Rarity = "Secret",
        Price = 20000000000,
        Generation = 70000000,
    },
    ["Spooky and Pumpky"] = {
        Name = "Spooky and Pumpky",
        DisplayName = "Spooky and Pumpky",
        Rarity = "Secret",
        Price = 25000000000,
        Generation = 80000000,
    },
    ["La Casa Boo"] = {
        Name = "La Casa Boo",
        DisplayName = "La Casa Boo",
        Rarity = "Secret",
        Price = 40000000000,
        Generation = 100000000,
    },
    ["Fragrama and Chocrama"] = {
        Name = "Fragrama and Chocrama",
        DisplayName = "Fragrama and Chocrama",
        Rarity = "Secret",
        Price = 40000000000,
        Generation = 100000000,
    },
    ["La Secret Combinasion"] = {
        Name = "La Secret Combinasion",
        DisplayName = "La Secret Combinasion",
        Rarity = "Secret",
        Price = 50000000000,
        Generation = 125000000,
    },
    ["Burguro And Fryuro"] = {
        Name = "Burguro And Fryuro",
        DisplayName = "Burguro And Fryuro",
        Rarity = "Secret",
        Price = 75000000000,
        Generation = 150000000,
    },
    ["Capitano Moby"] = {
        Name = "Capitano Moby",
        DisplayName = "Capitano Moby",
        Rarity = "Secret",
        Price = 125000000000,
        Generation = 160000000,
    },
    ["Headless Horseman"] = {
        Name = "Headless Horseman",
        DisplayName = "Headless Horseman",
        Rarity = "Secret",
        Price = 150000000000,
        Generation = 175000000,
    },
    ["Dragon Cannelloni"] = {
        Name = "Dragon Cannelloni",
        DisplayName = "Dragon Cannelloni",
        Rarity = "Secret",
        Price = 200000000000,
        Generation = 200000000,
    },
    ["Meowl"] = {
        Name = "Meowl",
        DisplayName = "Meowl",
        Rarity = "OG",
        Price = 350000000000,
        Generation = 300000000,
    },
    ["Strawberry Elephant"] = {
        Name = "Strawberry Elephant",
        DisplayName = "Strawberry Elephant",
        Rarity = "OG",
        Price = 500000000000,
        Generation = 350000000,
    },
}
return v7
