local v7 = {
    ["Los Lucky Blocks"] = {
        DisplayName = "Los Lucky Blocks",
        Price = 250000000,
        Generation = 0,
        Rarity = "Admin",
    },
    ["Lucky Block"] = {
        DisplayName = "Lucky Block",
        Price = 2500000,
        Generation = 0,
        Rarity = "Mythic",
    },
    ["Spooky Lucky Block"] = {
        DisplayName = "Spooky Lucky Block",
        Price = 350000000,
        Generation = 0,
        Rarity = "Spooky",
    },
    ["Los Taco Blocks"] = {
        DisplayName = "Los Taco Blocks",
        Price = 300000000,
        Generation = 0,
        Rarity = "Taco",
    },
    ["Lucky Block"] = {
        DisplayName = "Lucky Block",
        Price = 750000000,
        Generation = 0,
        Rarity = "Secret",
    },
    ["Lucky Block"] = {
        DisplayName = "Lucky Block",
        Price = 25000000,
        Generation = 0,
        Rarity = "Brainrot God",
    },
    ["Lucky Block"] = {
        DisplayName = "Lucky Block",
        Price = 50000000,
        Generation = 0,
        Rarity = "Taco",
    },
    ["Lucky Block"] = {
        DisplayName = "Lucky Block",
        Price = 100000000,
        Generation = 0,
        Rarity = "Admin",
    },
    ["Noobini Pizzanini"] = {
        DisplayName = "Noobini Pizzanini",
        Price = 25,
        Generation = 1,
        Rarity = "Common",
    },
    ["LirilÃ¬ LarilÃ "] = {
        DisplayName = "LirilÃ¬ LarilÃ ",
        Price = 250,
        Generation = 3,
        Rarity = "Common",
    },
    ["Tim Cheese"] = {
        DisplayName = "Tim Cheese",
        Price = 500,
        Generation = 5,
        Rarity = "Common",
    },
    ["Fluriflura"] = {
        DisplayName = "Fluriflura",
        Price = 750,
        Generation = 7,
        Rarity = "Common",
    },
    ["Talpa Di Fero"] = {
        DisplayName = "Talpa Di Fero",
        Price = 1000,
        Generation = 9,
        Rarity = "Common",
    },
    ["Svinina Bombardino"] = {
        DisplayName = "Svinina Bombardino",
        Price = 1250,
        Generation = 10,
        Rarity = "Common",
    },
    ["Raccooni Jandelini"] = {
        DisplayName = "Raccooni Jandelini",
        Price = 1350,
        Generation = 12,
        Rarity = "Common",
    },
    ["Tartaragno"] = {
        DisplayName = "Tartaragno",
        Price = 1500,
        Generation = 13,
        Rarity = "Common",
    },
    ["Pipi Kiwi"] = {
        DisplayName = "Pipi Kiwi",
        Price = 1500,
        Generation = 13,
        Rarity = "Common",
    },
    ["Pipi Corni"] = {
        DisplayName = "Pipi Corni",
        Price = 1750,
        Generation = 14,
        Rarity = "Common",
    },
    ["Trippi Troppi"] = {
        DisplayName = "Trippi Troppi",
        Price = 2000,
        Generation = 15,
        Rarity = "Rare",
    },
    ["Gangster Footera"] = {
        DisplayName = "Gangster Footera",
        Price = 4000,
        Generation = 30,
        Rarity = "Rare",
    },
    ["Bandito Bobritto"] = {
        DisplayName = "Bandito Bobritto",
        Price = 4500,
        Generation = 35,
        Rarity = "Rare",
    },
    ["Boneca Ambalabu"] = {
        DisplayName = "Boneca Ambalabu",
        Price = 5000,
        Generation = 40,
        Rarity = "Rare",
    },
    ["Cacto Hipopotamo"] = {
        DisplayName = "Cacto Hipopotamo",
        Price = 6500,
        Generation = 50,
        Rarity = "Rare",
    },
    ["Ta Ta Ta Ta Sahur"] = {
        DisplayName = "Ta Ta Ta Ta Sahur",
        Price = 7500,
        Generation = 55,
        Rarity = "Rare",
    },
    ["Cupcake Koala"] = {
        DisplayName = "Cupcake Koala",
        Price = 8000,
        Generation = 60,
        Rarity = "Rare",
    },
    ["Tric Trac Baraboom"] = {
        DisplayName = "Tric Trac Baraboom",
        Price = 9000,
        Generation = 65,
        Rarity = "Rare",
    },
    ["Pipi Avocado"] = {
        DisplayName = "Pipi Avocado",
        Price = 9500,
        Generation = 70,
        Rarity = "Rare",
    },
    ["Cappuccino Assassino"] = {
        DisplayName = "Cappuccino Assassino",
        Price = 10000,
        Generation = 75,
        Rarity = "Epic",
    },
    ["Pinealotto Fruttarino"] = {
        DisplayName = "Pinealotto Fruttarino",
        Price = 9750,
        Generation = 75,
        Rarity = "Rare",
    },
    ["Bandito Axolito"] = {
        DisplayName = "Bandito Axolito",
        Price = 12500,
        Generation = 90,
        Rarity = "Epic",
    },
    ["Brr Brr Patapim"] = {
        DisplayName = "Brr Brr Patapim",
        Price = 15000,
        Generation = 100,
        Rarity = "Epic",
    },
    ["Avocadini Antilopini"] = {
        DisplayName = "Avocadini Antilopini",
        Price = 17500,
        Generation = 115,
        Rarity = "Epic",
    },
    ["Trulimero Trulicina"] = {
        DisplayName = "Trulimero Trulicina",
        Price = 20000,
        Generation = 125,
        Rarity = "Epic",
    },
    ["Bambini Crostini"] = {
        DisplayName = "Bambini Crostini",
        Price = 22500,
        Generation = 135,
        Rarity = "Epic",
    },
    ["Malame Amarele"] = {
        DisplayName = "Malame Amarele",
        Price = 23500,
        Generation = 140,
        Rarity = "Epic",
    },
    ["Bananita Dolphinita"] = {
        DisplayName = "Bananita Dolphinita",
        Price = 25000,
        Generation = 150,
        Rarity = "Epic",
    },
    ["Perochello Lemonchello"] = {
        DisplayName = "Perochello Lemonchello",
        Price = 27500,
        Generation = 160,
        Rarity = "Epic",
    },
    ["Brri Brri Bicus Dicus Bombicus"] = {
        DisplayName = "Brri Brri Bicus Dicus Bombicus",
        Price = 30000,
        Generation = 175,
        Rarity = "Epic",
    },
    ["Burbaloni Loliloli"] = {
        DisplayName = "Burbaloni Loliloli",
        Price = 35000,
        Generation = 200,
        Rarity = "Legendary",
    },
    ["Avocadini Guffo"] = {
        DisplayName = "Avocadini Guffo",
        Price = 35000,
        Generation = 225,
        Rarity = "Epic",
    },
    ["Ti Ti Ti Sahur"] = {
        DisplayName = "Ti Ti Ti Sahur",
        Price = 37500,
        Generation = 225,
        Rarity = "Epic",
    },
    ["Mangolini Parrocini"] = {
        DisplayName = "Mangolini Parrocini",
        Price = 38500,
        Generation = 235,
        Rarity = "Epic",
    },
    ["Frogato Pirato"] = {
        DisplayName = "Frogato Pirato",
        Price = 39000,
        Generation = 240,
        Rarity = "Epic",
    },
    ["Salamino Penguino"] = {
        DisplayName = "Salamino Penguino",
        Price = 40000,
        Generation = 250,
        Rarity = "Epic",
    },
    ["Doi Doi Do"] = {
        DisplayName = "Doi Doi Do",
        Price = 41000,
        Generation = 260,
        Rarity = "Epic",
    },
    ["Wombo Rollo"] = {
        DisplayName = "Wombo Rollo",
        Price = 42500,
        Generation = 275,
        Rarity = "Epic",
    },
    ["Penguino Cocosino"] = {
        DisplayName = "Penguino Cocosino",
        Price = 45000,
        Generation = 300,
        Rarity = "Epic",
    },
    ["Chimpanzini Bananini"] = {
        DisplayName = "Chimpanzini Bananini",
        Price = 50000,
        Generation = 300,
        Rarity = "Legendary",
    },
    ["Mummio Rappitto"] = {
        DisplayName = "Mummio Rappitto",
        Price = 47500,
        Generation = 325,
        Rarity = "Epic",
    },
    ["Tirilikalika Tirilikalako"] = {
        DisplayName = "Tirilikalika Tirilikalako",
        Price = 75000,
        Generation = 450,
        Rarity = "Legendary",
    },
    ["Ballerina Cappuccina"] = {
        DisplayName = "Ballerina Cappuccina",
        Price = 100000,
        Generation = 500,
        Rarity = "Legendary",
    },
    ["Chef Crabracadabra"] = {
        DisplayName = "Chef Crabracadabra",
        Price = 150000,
        Generation = 600,
        Rarity = "Legendary",
    },
    ["Lionel Cactuseli"] = {
        DisplayName = "Lionel Cactuseli",
        Price = 175000,
        Generation = 650,
        Rarity = "Legendary",
    },
    ["Glorbo Fruttodrillo"] = {
        DisplayName = "Glorbo Fruttodrillo",
        Price = 200000,
        Generation = 750,
        Rarity = "Legendary",
    },
    ["Quivioli Ameleonni"] = {
        DisplayName = "Quivioli Ameleonni",
        Price = 225000,
        Generation = 900,
        Rarity = "Legendary",
    },
    ["Clickerino Crabo"] = {
        DisplayName = "Clickerino Crabo",
        Price = 250000,
        Generation = 1000,
        Rarity = "Legendary",
    },
    ["Blueberrinni Octopusini"] = {
        DisplayName = "Blueberrinni Octopusini",
        Price = 250000,
        Generation = 1000,
        Rarity = "Legendary",
    },
    ["Caramello Filtrello"] = {
        DisplayName = "Caramello Filtrello",
        Price = 255000,
        Generation = 1050,
        Rarity = "Legendary",
    },
    ["Pipi Potato"] = {
        DisplayName = "Pipi Potato",
        Price = 265000,
        Generation = 1100,
        Rarity = "Legendary",
    },
    ["Strawberrelli Flamingelli"] = {
        DisplayName = "Strawberrelli Flamingelli",
        Price = 275000,
        Generation = 1150,
        Rarity = "Legendary",
    },
    ["Cocosini Mama"] = {
        DisplayName = "Cocosini Mama",
        Price = 285000,
        Generation = 1200,
        Rarity = "Legendary",
    },
    ["Pandaccini Bananini"] = {
        DisplayName = "Pandaccini Bananini",
        Price = 300000,
        Generation = 1250,
        Rarity = "Legendary",
    },
    ["Quackula"] = {
        DisplayName = "Quackula",
        Price = 310000,
        Generation = 1275,
        Rarity = "Legendary",
    },
    ["Pi Pi Watermelon"] = {
        DisplayName = "Pi Pi Watermelon",
        Price = 315000,
        Generation = 1300,
        Rarity = "Legendary",
    },
    ["Signore Carapace"] = {
        DisplayName = "Signore Carapace",
        Price = 320000,
        Generation = 1325,
        Rarity = "Legendary",
    },
    ["Sigma Boy"] = {
        DisplayName = "Sigma Boy",
        Price = 325000,
        Generation = 1350,
        Rarity = "Legendary",
    },
    ["Puffaball"] = {
        DisplayName = "Puffaball",
        Price = 330000,
        Generation = 1500,
        Rarity = "Legendary",
    },
    ["Sigma Girl"] = {
        DisplayName = "Sigma Girl",
        Price = 340000,
        Generation = 1800,
        Rarity = "Legendary",
    },
    ["Buho de Fuego"] = {
        DisplayName = "Buho de Fuego",
        Price = 345000,
        Generation = 1850,
        Rarity = "Legendary",
    },
    ["Frigo Camelo"] = {
        DisplayName = "Frigo Camelo",
        Price = 350000,
        Generation = 1900,
        Rarity = "Mythic",
    },
    ["Orangutini Ananassini"] = {
        DisplayName = "Orangutini Ananassini",
        Price = 400000,
        Generation = 2000,
        Rarity = "Mythic",
    },
    ["Rhino Toasterino"] = {
        DisplayName = "Rhino Toasterino",
        Price = 450000,
        Generation = 2150,
        Rarity = "Mythic",
    },
    ["Bombardiro Crocodilo"] = {
        DisplayName = "Bombardiro Crocodilo",
        Price = 500000,
        Generation = 2500,
        Rarity = "Mythic",
    },
    ["Brutto Gialutto"] = {
        DisplayName = "Brutto Gialutto",
        Price = 600000,
        Generation = 3000,
        Rarity = "Mythic",
    },
    ["Spioniro Golubiro"] = {
        DisplayName = "Spioniro Golubiro",
        Price = 750000,
        Generation = 3500,
        Rarity = "Mythic",
    },
    ["Bombombini Gusini"] = {
        DisplayName = "Bombombini Gusini",
        Price = 1000000,
        Generation = 5000,
        Rarity = "Mythic",
    },
    ["Zibra Zubra Zibralini"] = {
        DisplayName = "Zibra Zubra Zibralini",
        Price = 1500000,
        Generation = 6000,
        Rarity = "Mythic",
    },
    ["Tigrilini Watermelini"] = {
        DisplayName = "Tigrilini Watermelini",
        Price = 1750000,
        Generation = 6500,
        Rarity = "Mythic",
    },
    ["Avocadorilla"] = {
        DisplayName = "Avocadorilla",
        Price = 2000000,
        Generation = 7000,
        Rarity = "Mythic",
    },
    ["Cavallo Virtuoso"] = {
        DisplayName = "Cavallo Virtuoso",
        Price = 2500000,
        Generation = 7500,
        Rarity = "Mythic",
    },
    ["Gorillo Subwoofero"] = {
        DisplayName = "Gorillo Subwoofero",
        Price = 2750000,
        Generation = 7750,
        Rarity = "Mythic",
    },
    ["Stoppo Luminino"] = {
        DisplayName = "Stoppo Luminino",
        Price = 3000000,
        Generation = 8000,
        Rarity = "Mythic",
    },
    ["Gorillo Watermelondrillo"] = {
        DisplayName = "Gorillo Watermelondrillo",
        Price = 3000000,
        Generation = 8000,
        Rarity = "Mythic",
    },
    ["Tob Tobi Tobi"] = {
        DisplayName = "Tob Tobi Tobi",
        Price = 3250000,
        Generation = 8500,
        Rarity = "Mythic",
    },
    ["Lerulerulerule"] = {
        DisplayName = "Lerulerulerule",
        Price = 3500000,
        Generation = 8750,
        Rarity = "Mythic",
    },
    ["Ganganzelli Trulala"] = {
        DisplayName = "Ganganzelli Trulala",
        Price = 3750000,
        Generation = 9000,
        Rarity = "Mythic",
    },
    ["Te Te Te Sahur"] = {
        DisplayName = "Te Te Te Sahur",
        Price = 4000000,
        Generation = 9500,
        Rarity = "Mythic",
    },
    ["Rhino Helicopterino"] = {
        DisplayName = "Rhino Helicopterino",
        Price = 4100000,
        Generation = 11000,
        Rarity = "Mythic",
    },
    ["Magi Ribbitini"] = {
        DisplayName = "Magi Ribbitini",
        Price = 4200000,
        Generation = 11500,
        Rarity = "Mythic",
    },
    ["Tracoducotulu Delapeladustuz"] = {
        DisplayName = "Tracoducotulu Delapeladustuz",
        Price = 4250000,
        Generation = 12000,
        Rarity = "Mythic",
    },
    ["Los Noobinis"] = {
        DisplayName = "Los Noobinis",
        Price = 4350000,
        Generation = 12500,
        Rarity = "Mythic",
    },
    ["Cachorrito Melonito"] = {
        DisplayName = "Cachorrito Melonito",
        Price = 4400000,
        Generation = 13000,
        Rarity = "Mythic",
    },
    ["Carloo"] = {
        DisplayName = "Carloo",
        Price = 4500000,
        Generation = 13500,
        Rarity = "Mythic",
    },
    ["Elefanto Frigo"] = {
        DisplayName = "Elefanto Frigo",
        Price = 4600000,
        Generation = 14000,
        Rarity = "Mythic",
    },
    ["Carrotini Brainini"] = {
        DisplayName = "Carrotini Brainini",
        Price = 4750000,
        Generation = 15000,
        Rarity = "Mythic",
    },
    ["Centrucci Nuclucci"] = {
        DisplayName = "Centrucci Nuclucci",
        Price = 4800000,
        Generation = 15500,
        Rarity = "Mythic",
    },
    ["Toiletto Focaccino"] = {
        DisplayName = "Toiletto Focaccino",
        Price = 4850000,
        Generation = 16000,
        Rarity = "Mythic",
    },
    ["Jacko Spaventosa"] = {
        DisplayName = "Jacko Spaventosa",
        Price = 4875000,
        Generation = 16250,
        Rarity = "Mythic",
    },
    ["Bananito Bandito"] = {
        DisplayName = "Bananito Bandito",
        Price = 4900000,
        Generation = 16500,
        Rarity = "Mythic",
    },
    ["Cocofanto Elefanto"] = {
        DisplayName = "Cocofanto Elefanto",
        Price = 5000000,
        Generation = 17500,
        Rarity = "Brainrot God",
    },
    ["Antonio"] = {
        DisplayName = "Antonio",
        Price = 6000000,
        Generation = 18500,
        Rarity = "Brainrot God",
    },
    ["Girafa Celestre"] = {
        DisplayName = "Girafa Celestre",
        Price = 7500000,
        Generation = 20000,
        Rarity = "Brainrot God",
    },
    ["Gattatino Nyanino"] = {
        DisplayName = "Gattatino Nyanino",
        Price = 7500000,
        Generation = 35000,
        Rarity = "Brainrot God",
    },
    ["Chihuanini Taconini"] = {
        DisplayName = "Chihuanini Taconini",
        Price = 8500000,
        Generation = 45000,
        Rarity = "Brainrot God",
    },
    ["Matteo"] = {
        DisplayName = "Matteo",
        Price = 10000000,
        Generation = 50000,
        Rarity = "Brainrot God",
    },
    ["Tralalero Tralala"] = {
        DisplayName = "Tralalero Tralala",
        Price = 10000000,
        Generation = 50000,
        Rarity = "Brainrot God",
    },
    ["Los Crocodillitos"] = {
        DisplayName = "Los Crocodillitos",
        Price = 12500000,
        Generation = 55000,
        Rarity = "Brainrot God",
    },
    ["Tigroligre Frutonni"] = {
        DisplayName = "Tigroligre Frutonni",
        Price = 14000000,
        Generation = 60000,
        Rarity = "Brainrot God",
    },
    ["Money Money Man"] = {
        DisplayName = "Money Money Man",
        Price = 17500000,
        Generation = 65000,
        Rarity = "Brainrot God",
    },
    ["Espresso Signora"] = {
        DisplayName = "Espresso Signora",
        Price = 25000000,
        Generation = 70000,
        Rarity = "Brainrot God",
    },
    ["Odin Din Din Dun"] = {
        DisplayName = "Odin Din Din Dun",
        Price = 15000000,
        Generation = 75000,
        Rarity = "Brainrot God",
    },
    ["Unclito Samito"] = {
        DisplayName = "Unclito Samito",
        Price = 20000000,
        Generation = 75000,
        Rarity = "Brainrot God",
    },
    ["Tipi Topi Taco"] = {
        DisplayName = "Tipi Topi Taco",
        Price = 20000000,
        Generation = 75000,
        Rarity = "Brainrot God",
    },
    ["Alessio"] = {
        DisplayName = "Alessio",
        Price = 17500000,
        Generation = 85000,
        Rarity = "Brainrot God",
    },
    ["Tukanno Bananno"] = {
        DisplayName = "Tukanno Bananno",
        Price = 22500000,
        Generation = 100000,
        Rarity = "Brainrot God",
    },
    ["Tralalita Tralala"] = {
        DisplayName = "Tralalita Tralala",
        Price = 20000000,
        Generation = 100000,
        Rarity = "Brainrot God",
    },
    ["Orcalero Orcala"] = {
        DisplayName = "Orcalero Orcala",
        Price = 25000000,
        Generation = 100000,
        Rarity = "Brainrot God",
    },
    ["Vampira Cappucina"] = {
        DisplayName = "Vampira Cappucina",
        Price = 24500000,
        Generation = 125000,
        Rarity = "Brainrot God",
    },
    ["Extinct Ballerina"] = {
        DisplayName = "Extinct Ballerina",
        Price = 23500000,
        Generation = 125000,
        Rarity = "Brainrot God",
    },
    ["Trenostruzzo Turbo 3000"] = {
        DisplayName = "Trenostruzzo Turbo 3000",
        Price = 25000000,
        Generation = 150000,
        Rarity = "Brainrot God",
    },
    ["Jacko Jack Jack"] = {
        DisplayName = "Jacko Jack Jack",
        Price = 30000000,
        Generation = 150000,
        Rarity = "Brainrot God",
    },
    ["Urubini Flamenguini"] = {
        DisplayName = "Urubini Flamenguini",
        Price = 30000000,
        Generation = 150000,
        Rarity = "Brainrot God",
    },
    ["Capi Taco"] = {
        DisplayName = "Capi Taco",
        Price = 31000000,
        Generation = 155000,
        Rarity = "Brainrot God",
    },
    ["Los Chihuaninis"] = {
        DisplayName = "Los Chihuaninis",
        Price = 32000000,
        Generation = 160000,
        Rarity = "Brainrot God",
    },
    ["Gattito Tacoto"] = {
        DisplayName = "Gattito Tacoto",
        Price = 32500000,
        Generation = 165000,
        Rarity = "Brainrot God",
    },
    ["Trippi Troppi Troppa Trippa"] = {
        DisplayName = "Trippi Troppi Troppa Trippa",
        Price = 30000000,
        Generation = 175000,
        Rarity = "Brainrot God",
    },
    ["Las Capuchinas"] = {
        DisplayName = "Las Capuchinas",
        Price = 32500000,
        Generation = 185000,
        Rarity = "Brainrot God",
    },
    ["Ballerino Lololo"] = {
        DisplayName = "Ballerino Lololo",
        Price = 35000000,
        Generation = 200000,
        Rarity = "Brainrot God",
    },
    ["Bulbito Bandito Traktorito"] = {
        DisplayName = "Bulbito Bandito Traktorito",
        Price = 35000000,
        Generation = 205000,
        Rarity = "Brainrot God",
    },
    ["Los Tungtungtungcitos"] = {
        DisplayName = "Los Tungtungtungcitos",
        Price = 37500000,
        Generation = 210000,
        Rarity = "Brainrot God",
    },
    ["Pakrahmatmamat"] = {
        DisplayName = "Pakrahmatmamat",
        Price = 37500000,
        Generation = 215000,
        Rarity = "Brainrot God",
    },
    ["Los Bombinitos"] = {
        DisplayName = "Los Bombinitos",
        Price = 42500000,
        Generation = 220000,
        Rarity = "Brainrot God",
    },
    ["Pakrahmatmatina"] = {
        DisplayName = "Pakrahmatmatina",
        Price = 40500000,
        Generation = 225000,
        Rarity = "Brainrot God",
    },
    ["Brr es Teh Patipum"] = {
        DisplayName = "Brr es Teh Patipum",
        Price = 40000000,
        Generation = 225000,
        Rarity = "Brainrot God",
    },
    ["Bombardini Tortinii"] = {
        DisplayName = "Bombardini Tortinii",
        Price = 50000000,
        Generation = 225000,
        Rarity = "Brainrot God",
    },
    ["Piccione Macchina"] = {
        DisplayName = "Piccione Macchina",
        Price = 40000000,
        Generation = 225000,
        Rarity = "Brainrot God",
    },
    ["Tractoro Dinosauro"] = {
        DisplayName = "Tractoro Dinosauro",
        Price = 42500000,
        Generation = 230000,
        Rarity = "Brainrot God",
    },
    ["Los Orcalitos"] = {
        DisplayName = "Los Orcalitos",
        Price = 45000000,
        Generation = 235000,
        Rarity = "Brainrot God",
    },
    ["Crabbo Limonetta"] = {
        DisplayName = "Crabbo Limonetta",
        Price = 46000000,
        Generation = 235000,
        Rarity = "Brainrot God",
    },
    ["Orcalita Orcala"] = {
        DisplayName = "Orcalita Orcala",
        Price = 45000000,
        Generation = 240000,
        Rarity = "Brainrot God",
    },
    ["Cacasito Satalito"] = {
        DisplayName = "Cacasito Satalito",
        Price = 45000000,
        Generation = 240000,
        Rarity = "Brainrot God",
    },
    ["Aquanaut"] = {
        DisplayName = "Aquanaut",
        Price = 45500000,
        Generation = 245000,
        Rarity = "Brainrot God",
    },
    ["Tartaruga Cisterna"] = {
        DisplayName = "Tartaruga Cisterna",
        Price = 45000000,
        Generation = 250000,
        Rarity = "Brainrot God",
    },
    ["Snailenzo"] = {
        DisplayName = "Snailenzo",
        Price = 45000000,
        Generation = 250000,
        Rarity = "Brainrot God",
    },
    ["Mummy Ambalabu"] = {
        DisplayName = "Mummy Ambalabu",
        Price = 45000000,
        Generation = 250000,
        Rarity = "Brainrot God",
    },
    ["Corn Corn Corn Sahur"] = {
        DisplayName = "Corn Corn Corn Sahur",
        Price = 45000000,
        Generation = 250000,
        Rarity = "Brainrot God",
    },
    ["Squalanana"] = {
        DisplayName = "Squalanana",
        Price = 45000000,
        Generation = 250000,
        Rarity = "Brainrot God",
    },
    ["Dug dug dug"] = {
        DisplayName = "Dug dug dug",
        Price = 45500000,
        Generation = 255000,
        Rarity = "Brainrot God",
    },
    ["Granchiello Spiritell"] = {
        DisplayName = "Granchiello Spiritell",
        Price = 46000000,
        Generation = 260000,
        Rarity = "Brainrot God",
    },
    ["Los Tipi Tacos"] = {
        DisplayName = "Los Tipi Tacos",
        Price = 46000000,
        Generation = 260000,
        Rarity = "Brainrot God",
    },
    ["Frio Ninja"] = {
        DisplayName = "Frio Ninja",
        Price = 46500000,
        Generation = 265000,
        Rarity = "Brainrot God",
    },
    ["Piccionetta Macchina"] = {
        DisplayName = "Piccionetta Macchina",
        Price = 47000000,
        Generation = 270000,
        Rarity = "Brainrot God",
    },
    ["Mastodontico Telepiedone"] = {
        DisplayName = "Mastodontico Telepiedone",
        Price = 47500000,
        Generation = 275000,
        Rarity = "Brainrot God",
    },
    ["Bambu Bambu Sahur"] = {
        DisplayName = "Bambu Bambu Sahur",
        Price = 47500000,
        Generation = 275000,
        Rarity = "Brainrot God",
    },
    ["Los Gattitos"] = {
        DisplayName = "Los Gattitos",
        Price = 47500000,
        Generation = 275000,
        Rarity = "Brainrot God",
    },
    ["Noo La Polizia"] = {
        DisplayName = "Noo La Polizia",
        Price = 67000000,
        Generation = 280000,
        Rarity = "Brainrot God",
    },
    ["Anpali Babel"] = {
        DisplayName = "Anpali Babel",
        Price = 48000000,
        Generation = 280000,
        Rarity = "Brainrot God",
    },
    ["Cappuccino Clownino"] = {
        DisplayName = "Cappuccino Clownino",
        Price = 48500000,
        Generation = 285000,
        Rarity = "Brainrot God",
    },
    ["Brasilini Berimbini"] = {
        DisplayName = "Brasilini Berimbini",
        Price = 55000000,
        Generation = 285000,
        Rarity = "Brainrot God",
    },
    ["Krupuk Pagi Pagi"] = {
        DisplayName = "Krupuk Pagi Pagi",
        Price = 60000000,
        Generation = 290000,
        Rarity = "Brainrot God",
    },
    ["Belula Beluga"] = {
        DisplayName = "Belula Beluga",
        Price = 60000000,
        Generation = 290000,
        Rarity = "Brainrot God",
    },
    ["Skull Skull Skull"] = {
        DisplayName = "Skull Skull Skull",
        Price = 60000000,
        Generation = 290000,
        Rarity = "Brainrot God",
    },
    ["Tentacolo Tecnico"] = {
        DisplayName = "Tentacolo Tecnico",
        Price = 62500000,
        Generation = 292500,
        Rarity = "Brainrot God",
    },
    ["Pop Pop Sahur"] = {
        DisplayName = "Pop Pop Sahur",
        Price = 65000000,
        Generation = 295000,
        Rarity = "Brainrot God",
    },
    ["Bisonte Giuppitere"] = {
        DisplayName = "Bisonte Giuppitere",
        Price = 75000000,
        Generation = 300000,
        Rarity = "Secret",
    },
    ["Los Matteos"] = {
        DisplayName = "Los Matteos",
        Price = 100000000,
        Generation = 300000,
        Rarity = "Secret",
    },
    ["Karkerkar Kurkur"] = {
        DisplayName = "Karkerkar Kurkur",
        Price = 100000000,
        Generation = 300000,
        Rarity = "Secret",
    },
    ["La Vacca Saturno Saturnita"] = {
        DisplayName = "La Vacca Saturno Saturnita",
        Price = 50000000,
        Generation = 300000,
        Rarity = "Secret",
    },
    ["Trenostruzzo Turbo 4000"] = {
        DisplayName = "Trenostruzzo Turbo 4000",
        Price = 100000000,
        Generation = 310000,
        Rarity = "Secret",
    },
    ["Jackorilla"] = {
        DisplayName = "Jackorilla",
        Price = 80000000,
        Generation = 315000,
        Rarity = "Secret",
    },
    ["Sammyni Spyderini"] = {
        DisplayName = "Sammyni Spyderini",
        Price = 75000000,
        Generation = 325000,
        Rarity = "Secret",
    },
    ["Torrtuginni Dragonfrutini"] = {
        DisplayName = "Torrtuginni Dragonfrutini",
        Price = 125000000,
        Generation = 350000,
        Rarity = "Secret",
    },
    ["Dul Dul Dul"] = {
        DisplayName = "Dul Dul Dul",
        Price = 150000000,
        Generation = 375000,
        Rarity = "Secret",
    },
    ["Chachechi"] = {
        DisplayName = "Chachechi",
        Price = 85000000,
        Generation = 400000,
        Rarity = "Secret",
    },
    ["Blackhole Goat"] = {
        DisplayName = "Blackhole Goat",
        Price = 75000000,
        Generation = 400000,
        Rarity = "Secret",
    },
    ["Agarrini la Palini"] = {
        DisplayName = "Agarrini la Palini",
        Price = 80000000,
        Generation = 425000,
        Rarity = "Secret",
    },
    ["Los Spyderinis"] = {
        DisplayName = "Los Spyderinis",
        Price = 125000000,
        Generation = 425000,
        Rarity = "Secret",
    },
    ["Fragola La La La"] = {
        DisplayName = "Fragola La La La",
        Price = 125000000,
        Generation = 450000,
        Rarity = "Secret",
    },
    ["Extinct Tralalero"] = {
        DisplayName = "Extinct Tralalero",
        Price = 125000000,
        Generation = 450000,
        Rarity = "Secret",
    },
    ["La Cucaracha"] = {
        DisplayName = "La Cucaracha",
        Price = 110000000,
        Generation = 475000,
        Rarity = "Secret",
    },
    ["Los Tortus"] = {
        DisplayName = "Los Tortus",
        Price = 100000000,
        Generation = 500000,
        Rarity = "Secret",
    },
    ["Los Tralaleritos"] = {
        DisplayName = "Los Tralaleritos",
        Price = 100000000,
        Generation = 500000,
        Rarity = "Secret",
    },
    ["Vulturino Skeletono"] = {
        DisplayName = "Vulturino Skeletono",
        Price = 110000000,
        Generation = 500000,
        Rarity = "Secret",
    },
    ["Zombie Tralala"] = {
        DisplayName = "Zombie Tralala",
        Price = 100000000,
        Generation = 500000,
        Rarity = "Secret",
    },
    ["Boatito Auratito"] = {
        DisplayName = "Boatito Auratito",
        Price = 115000000,
        Generation = 525000,
        Rarity = "Secret",
    },
    ["Guerriro Digitale"] = {
        DisplayName = "Guerriro Digitale",
        Price = 120000000,
        Generation = 550000,
        Rarity = "Secret",
    },
    ["Yess my examine"] = {
        DisplayName = "Yess my examine",
        Price = 130000000,
        Generation = 575000,
        Rarity = "Secret",
    },
    ["La Karkerkar Combinasion"] = {
        DisplayName = "La Karkerkar Combinasion",
        Price = 160000000,
        Generation = 600000,
        Rarity = "Secret",
    },
    ["Extinct Matteo"] = {
        DisplayName = "Extinct Matteo",
        Price = 140000000,
        Generation = 625000,
        Rarity = "Secret",
    },
    ["Pumpkini Spyderini"] = {
        DisplayName = "Pumpkini Spyderini",
        Price = 165000000,
        Generation = 650000,
        Rarity = "Secret",
    },
    ["Las Tralaleritas"] = {
        DisplayName = "Las Tralaleritas",
        Price = 150000000,
        Generation = 650000,
        Rarity = "Secret",
    },
    ["Job Job Job Sahur"] = {
        DisplayName = "Job Job Job Sahur",
        Price = 175000000,
        Generation = 700000,
        Rarity = "Secret",
    },
    ["Frankentteo"] = {
        DisplayName = "Frankentteo",
        Price = 175000000,
        Generation = 700000,
        Rarity = "Secret",
    },
    ["Karker Sahur"] = {
        DisplayName = "Karker Sahur",
        Price = 185000000,
        Generation = 725000,
        Rarity = "Secret",
    },
    ["Los Karkeritos"] = {
        DisplayName = "Los Karkeritos",
        Price = 200000000,
        Generation = 750000,
        Rarity = "Secret",
    },
    ["Las Vaquitas Saturnitas"] = {
        DisplayName = "Las Vaquitas Saturnitas",
        Price = 200000000,
        Generation = 750000,
        Rarity = "Secret",
    },
    ["La Vacca Jacko Linterino"] = {
        DisplayName = "La Vacca Jacko Linterino",
        Price = 225000000,
        Generation = 850000,
        Rarity = "Secret",
    },
    ["Trickolino"] = {
        DisplayName = "Trickolino",
        Price = 235000000,
        Generation = 900000,
        Rarity = "Secret",
    },
    ["Perrito Burrito"] = {
        DisplayName = "Perrito Burrito",
        Price = 250000000,
        Generation = 1000000,
        Rarity = "Secret",
    },
    ["Graipuss Medussi"] = {
        DisplayName = "Graipuss Medussi",
        Price = 250000000,
        Generation = 1000000,
        Rarity = "Secret",
    },
    ["1x1x1x1"] = {
        DisplayName = "1x1x1x1",
        Price = 255555555,
        Generation = 1111111,
        Rarity = "Secret",
    },
    ["Los Cucarachas"] = {
        DisplayName = "Los Cucarachas",
        Price = 300000000,
        Generation = 1250000,
        Rarity = "Secret",
    },
    ["Cuadramat and Pakrahmatmamat"] = {
        DisplayName = "Cuadramat and Pakrahmatmamat",
        Price = 400000000,
        Generation = 1400000,
        Rarity = "Secret",
    },
    ["Nooo My Hotspot"] = {
        DisplayName = "Nooo My Hotspot",
        Price = 500000000,
        Generation = 1500000,
        Rarity = "Secret",
    },
    ["Los Jobcitos"] = {
        DisplayName = "Los Jobcitos",
        Price = 500000000,
        Generation = 1500000,
        Rarity = "Secret",
    },
    ["Noo my examine"] = {
        DisplayName = "Noo my examine",
        Price = 525000000,
        Generation = 1750000,
        Rarity = "Secret",
    },
    ["La Sahur Combinasion"] = {
        DisplayName = "La Sahur Combinasion",
        Price = 550000000,
        Generation = 2000000,
        Rarity = "Secret",
    },
    ["Telemorte"] = {
        DisplayName = "Telemorte",
        Price = 550000000,
        Generation = 2000000,
        Rarity = "Secret",
    },
    ["To to to Sahur"] = {
        DisplayName = "To to to Sahur",
        Price = 575000000,
        Generation = 2250000,
        Rarity = "Secret",
    },
    ["Pot Hotspot"] = {
        DisplayName = "Pot Hotspot",
        Price = 600000000,
        Generation = 2500000,
        Rarity = "Secret",
    },
    ["Pirulitoita Bicicleteira"] = {
        DisplayName = "Pirulitoita Bicicleteira",
        Price = 600000000,
        Generation = 2500000,
        Rarity = "Secret",
    },
    ["Horegini Boom"] = {
        DisplayName = "Horegini Boom",
        Price = 650000000,
        Generation = 2750000,
        Rarity = "Secret",
    },
    ["Quesadilla Crocodila"] = {
        DisplayName = "Quesadilla Crocodila",
        Price = 700000000,
        Generation = 3000000,
        Rarity = "Secret",
    },
    ["Pot Pumpkin"] = {
        DisplayName = "Pot Pumpkin",
        Price = 700000000,
        Generation = 3000000,
        Rarity = "Secret",
    },
    ["Quesadillo Vampiro"] = {
        DisplayName = "Quesadillo Vampiro",
        Price = 750000000,
        Generation = 3500000,
        Rarity = "Secret",
    },
    ["Chicleteira Bicicleteira"] = {
        DisplayName = "Chicleteira Bicicleteira",
        Price = 750000000,
        Generation = 3500000,
        Rarity = "Secret",
    },
    ["Burrito Bandito"] = {
        DisplayName = "Burrito Bandito",
        Price = 850000000,
        Generation = 4000000,
        Rarity = "Secret",
    },
    ["Chicleteirina Bicicleteirina"] = {
        DisplayName = "Chicleteirina Bicicleteirina",
        Price = 850000000,
        Generation = 4000000,
        Rarity = "Secret",
    },
    ["Los Quesadillas"] = {
        DisplayName = "Los Quesadillas",
        Price = 875000000,
        Generation = 4500000,
        Rarity = "Secret",
    },
    ["Noo my Candy"] = {
        DisplayName = "Noo my Candy",
        Price = 900000000,
        Generation = 5000000,
        Rarity = "Secret",
    },
    ["Los Nooo My Hotspotsitos"] = {
        DisplayName = "Los Nooo My Hotspotsitos",
        Price = 1000000000,
        Generation = 5500000,
        Rarity = "Secret",
    },
    ["Rang Ring Bus"] = {
        DisplayName = "Rang Ring Bus",
        Price = 1100000000,
        Generation = 6000000,
        Rarity = "Secret",
    },
    ["Guest 666"] = {
        DisplayName = "Guest 666",
        Price = 1166666666,
        Generation = 6666666,
        Rarity = "Secret",
    },
    ["Los Chicleteiras"] = {
        DisplayName = "Los Chicleteiras",
        Price = 1200000000,
        Generation = 7000000,
        Rarity = "Secret",
    },
    ["67"] = {
        DisplayName = "67",
        Price = 1250000000,
        Generation = 7500000,
        Rarity = "Secret",
    },
    ["Los Burritos"] = {
        DisplayName = "Los Burritos",
        Price = 1400000000,
        Generation = 8500000,
        Rarity = "Secret",
    },
    ["La Grande Combinasion"] = {
        DisplayName = "La Grande Combinasion",
        Price = 1000000000,
        Generation = 10000000,
        Rarity = "Secret",
    },
    ["Mariachi Corazoni"] = {
        DisplayName = "Mariachi Corazoni",
        Price = 1750000000,
        Generation = 12500000,
        Rarity = "Secret",
    },
    ["Swag Soda"] = {
        DisplayName = "Swag Soda",
        Price = 1800000000,
        Generation = 13000000,
        Rarity = "Secret",
    },
    ["Los Combinasionas"] = {
        DisplayName = "Los Combinasionas",
        Price = 2000000000,
        Generation = 15000000,
        Rarity = "Secret",
    },
    ["Nuclearo Dinossauro"] = {
        DisplayName = "Nuclearo Dinossauro",
        Price = 2500000000,
        Generation = 15000000,
        Rarity = "Secret",
    },
    ["Fishino Clownino"] = {
        DisplayName = "Fishino Clownino",
        Price = 2100000000,
        Generation = 15500000,
        Rarity = "Secret",
    },
    ["Tacorita Bicicleta"] = {
        DisplayName = "Tacorita Bicicleta",
        Price = 2250000000,
        Generation = 16500000,
        Rarity = "Secret",
    },
    ["Las Sis"] = {
        DisplayName = "Las Sis",
        Price = 2500000000,
        Generation = 17500000,
        Rarity = "Secret",
    },
    ["Los Planitos"] = {
        DisplayName = "Los Planitos",
        Price = 2750000000,
        Generation = 18500000,
        Rarity = "Secret",
    },
    ["Los Hotspotsitos"] = {
        DisplayName = "Los Hotspotsitos",
        Price = 3000000000,
        Generation = 20000000,
        Rarity = "Secret",
    },
    ["Los Spooky Combinasionas"] = {
        DisplayName = "Los Spooky Combinasionas",
        Price = 3000000000,
        Generation = 20000000,
        Rarity = "Secret",
    },
    ["Money Money Puggy"] = {
        DisplayName = "Money Money Puggy",
        Price = 2600000000,
        Generation = 21000000,
        Rarity = "Secret",
    },
    ["Los Mobilis"] = {
        DisplayName = "Los Mobilis",
        Price = 2700000000,
        Generation = 22000000,
        Rarity = "Secret",
    },
    ["Celularcini Viciosini"] = {
        DisplayName = "Celularcini Viciosini",
        Price = 2750000000,
        Generation = 22500000,
        Rarity = "Secret",
    },
    ["Los 67"] = {
        DisplayName = "Los 67",
        Price = 2750000000,
        Generation = 22500000,
        Rarity = "Secret",
    },
    ["La Extinct Grande"] = {
        DisplayName = "La Extinct Grande",
        Price = 3250000000,
        Generation = 23500000,
        Rarity = "Secret",
    },
    ["Los Bros"] = {
        DisplayName = "Los Bros",
        Price = 2600000000,
        Generation = 24000000,
        Rarity = "Secret",
    },
    ["La Spooky Grande"] = {
        DisplayName = "La Spooky Grande",
        Price = 2900000000,
        Generation = 24500000,
        Rarity = "Secret",
    },
    ["Chipso and Queso"] = {
        DisplayName = "Chipso and Queso",
        Price = 2500000000,
        Generation = 25000000,
        Rarity = "Secret",
    },
    ["Chillin Chili"] = {
        DisplayName = "Chillin Chili",
        Price = 2500000000,
        Generation = 25000000,
        Rarity = "Secret",
    },
    ["Mieteteira Bicicleteira"] = {
        DisplayName = "Mieteteira Bicicleteira",
        Price = 2750000000,
        Generation = 26000000,
        Rarity = "Secret",
    },
    ["Tralaledon"] = {
        DisplayName = "Tralaledon",
        Price = 3000000000,
        Generation = 27500000,
        Rarity = "Secret",
    },
    ["Los Puggies"] = {
        DisplayName = "Los Puggies",
        Price = 3000000000,
        Generation = 30000000,
        Rarity = "Secret",
    },
    ["Esok Sekolah"] = {
        DisplayName = "Esok Sekolah",
        Price = 3500000000,
        Generation = 30000000,
        Rarity = "Secret",
    },
    ["W or L"] = {
        DisplayName = "W or L",
        Price = 3000000000,
        Generation = 30000000,
        Rarity = "Secret",
    },
    ["Los Primos"] = {
        DisplayName = "Los Primos",
        Price = 3750000000,
        Generation = 31000000,
        Rarity = "Secret",
    },
    ["Eviledon"] = {
        DisplayName = "Eviledon",
        Price = 3850000000,
        Generation = 31500000,
        Rarity = "Secret",
    },
    ["Los Tacoritas"] = {
        DisplayName = "Los Tacoritas",
        Price = 4000000000,
        Generation = 32000000,
        Rarity = "Secret",
    },
    ["Tang Tang Keletang"] = {
        DisplayName = "Tang Tang Keletang",
        Price = 4500000000,
        Generation = 33500000,
        Rarity = "Secret",
    },
    ["La Taco Combinasion"] = {
        DisplayName = "La Taco Combinasion",
        Price = 5000000000,
        Generation = 35000000,
        Rarity = "Secret",
    },
    ["Ketupat Kepat"] = {
        DisplayName = "Ketupat Kepat",
        Price = 5000000000,
        Generation = 35000000,
        Rarity = "Secret",
    },
    ["Tictac Sahur"] = {
        DisplayName = "Tictac Sahur",
        Price = 6000000000,
        Generation = 37500000,
        Rarity = "Secret",
    },
    ["La Supreme Combinasion"] = {
        DisplayName = "La Supreme Combinasion",
        Price = 7000000000,
        Generation = 40000000,
        Rarity = "Secret",
    },
    ["Orcaledon"] = {
        DisplayName = "Orcaledon",
        Price = 7000000000,
        Generation = 40000000,
        Rarity = "Secret",
    },
    ["Ketchuru and Musturu"] = {
        DisplayName = "Ketchuru and Musturu",
        Price = 7500000000,
        Generation = 42500000,
        Rarity = "Secret",
    },
    ["Lavadorito Spinito"] = {
        DisplayName = "Lavadorito Spinito",
        Price = 30000000000,
        Generation = 45000000,
        Rarity = "Secret",
    },
    ["Garama and Madundung"] = {
        DisplayName = "Garama and Madundung",
        Price = 10000000000,
        Generation = 50000000,
        Rarity = "Secret",
    },
    ["Spaghetti Tualetti"] = {
        DisplayName = "Spaghetti Tualetti",
        Price = 15000000000,
        Generation = 60000000,
        Rarity = "Secret",
    },
    ["Los Spaghettis"] = {
        DisplayName = "Los Spaghettis",
        Price = 20000000000,
        Generation = 70000000,
        Rarity = "Secret",
    },
    ["Spooky and Pumpky"] = {
        DisplayName = "Spooky and Pumpky",
        Price = 25000000000,
        Generation = 80000000,
        Rarity = "Secret",
    },
    ["La Casa Boo"] = {
        DisplayName = "La Casa Boo",
        Price = 40000000000,
        Generation = 100000000,
        Rarity = "Secret",
    },
    ["Fragrama and Chocrama"] = {
        DisplayName = "Fragrama and Chocrama",
        Price = 40000000000,
        Generation = 100000000,
        Rarity = "Secret",
    },
    ["La Secret Combinasion"] = {
        DisplayName = "La Secret Combinasion",
        Price = 50000000000,
        Generation = 125000000,
        Rarity = "Secret",
    },
    ["Burguro And Fryuro"] = {
        DisplayName = "Burguro And Fryuro",
        Price = 75000000000,
        Generation = 150000000,
        Rarity = "Secret",
    },
    ["Capitano Moby"] = {
        DisplayName = "Capitano Moby",
        Price = 125000000000,
        Generation = 160000000,
        Rarity = "Secret",
    },
    ["Headless Horseman"] = {
        DisplayName = "Headless Horseman",
        Price = 150000000000,
        Generation = 175000000,
        Rarity = "Secret",
    },
    ["Dragon Cannelloni"] = {
        DisplayName = "Dragon Cannelloni",
        Price = 250000000000,
        Generation = 250000000,
        Rarity = "Secret",
    },
    ["Meowl"] = {
        DisplayName = "Meowl",
        Price = 400000000000,
        Generation = 400000000,
        Rarity = "OG",
    },
    ["Strawberry Elephant"] = {
        DisplayName = "Strawberry Elephant",
        Price = 500000000000,
        Generation = 500000000,
        Rarity = "OG",
    },
}

return v7
