local PossibleDrops = {
    {Name = "Bacon", Drops = {"Wood", "Bandage", "Bacon"}},
    {Name = "Bacon Chicken", Drops = {"Egg"}},
    {Name = "Bacon Clown", Drops = {"Orb Spirit"}},
    {Name = "Bacon Farmer", Drops = {"Grains of Rice"}},
    {Name = "Bacon Fawkes", Drops = {"Gold", "Black Belt"}},
    {Name = "Bacon Fisherman", Drops = {"Fish"}},
    {Name = "Bacon Hellfire", Drops = {"Orb Dragon", "Dragon Fang"}},
    {Name = "Bacon Horse", Drops = {"Carrot", "Orb Yellow", "Orb Blue"}},
    {Name = "Bacon Ice", Drops = {"Cursed Wood", "Cursed Iron"}},
    {Name = "Bacon Iron", Drops = {"Holy Iron"}},
    {Name = "Bacon Kryptonite", Drops = {"Wind Stone", "Orb Red"}},
    {Name = "Bacon Lava", Drops = {"Orb Fire"}},
    {Name = "Bacon Marine", Drops = {"Chef Hat", "Black Shoes"}},
    {Name = "Bacon Marine Captain", Drops = {"Holy Wood", "Orb Green"}},
    {Name = "Bacon Minerals", Drops = {"Holy Gold", "Black Iron"}},
    {Name = "Bacon Pirate", Drops = {"Iron Shark Teeth"}},
    {Name = "Bacon Rock", Drops = {"Holy Stone"}},
    {Name = "Bacon Seinen", Drops = {"Shadow Diary", "Scarf Old"}},
    {Name = "Bacon Shadow Garden", Drops = {"Shadow Iron", "Orb Purple"}},
    {Name = "Bacon Snow", Drops = {"Khaw Phad Kai", "Book of Rokuogan"}},
    {Name = "Bacon Strong", Drops = {"Boxing Gloves", "Boxing Sandbag", "Dumbbell 25 KG"}},
    {Name = "Bacon Tarzan", Drops = {"Old Rock", "Old Wood"}},
    {Name = "Bacon The Deep", Drops = {"Orb Water"}},
    {Name = "Bacon Trainer", Drops = {"Trainer Notes", "Stopwatch"}},
    {Name = "Bacon Traveler", Drops = {"Pipe", "Iron"}},
    {Name = "Boss", Drops = {}},
    {Name = "Gorilla", Drops = {"Orb Black", "Old Iron"}},
}
