local PossibleDrops = {
    {Name = "Bacon", Drops = {"Bacon", "Bandage", "Wood"}},
    {Name = "Bacon Clown", Drops = {"Orb Spirit"}},
    {Name = "Bacon Fawkes", Drops = {"Black Belt", "Gold"}},
    {Name = "Bacon Fisherman", Drops = {"Fish"}},
    {Name = "Bacon Hellfire", Drops = {"Dragon Fang", "Orb Dragon"}},
    {Name = "Bacon Ice", Drops = {"Cursed Iron", "Cursed Wood"}},
    {Name = "Bacon Iron", Drops = {"Holy Iron"}},
    {Name = "Bacon Kryptonite", Drops = {"Orb Red", "Wind Stone"}},
    {Name = "Bacon Lava", Drops = {"Orb Fire"}},
    {Name = "Bacon Marine", Drops = {"Black Shoes", "Chef Hat"}},
    {Name = "Bacon Marine Captain", Drops = {"Holy Wood", "Orb Green"}},
    {Name = "Bacon Minerals", Drops = {"Black Iron", "Holy Gold"}},
    {Name = "Bacon Pirate", Drops = {"Iron Shark Teeth"}},
    {Name = "Bacon Rock", Drops = {"Holy Stone"}},
    {Name = "Bacon Seinen", Drops = {"Scarf Old", "Shadow Diary"}},
    {Name = "Bacon Shadow Garden", Drops = {"Orb Purple", "Shadow Iron"}},
    {Name = "Bacon Snow", Drops = {"Book of Rokuogan", "Khaw Phad Kai"}},
    {Name = "Bacon Strong", Drops = {"Boxing Gloves", "Boxing Sandbag", "Dumbbell 25 KG"}},
    {Name = "Bacon Tarzan", Drops = {"Old Rock", "Old Wood"}},
    {Name = "Bacon The Deep", Drops = {"Orb Water"}},
    {Name = "Bacon Traveler", Drops = {"Iron", "Pipe"}},
    {Name = "Gorilla", Drops = {"Old Iron", "Orb Black"}},
}
